// Code generated by ent, DO NOT EDIT.

package wallettransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/internal/types"
)

const (
	// Label holds the string label denoting the wallettransaction type in the database.
	Label = "wallet_transaction"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldEnvironmentID holds the string denoting the environment_id field in the database.
	FieldEnvironmentID = "environment_id"
	// FieldWalletID holds the string denoting the wallet_id field in the database.
	FieldWalletID = "wallet_id"
	// FieldCustomerID holds the string denoting the customer_id field in the database.
	FieldCustomerID = "customer_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldCreditAmount holds the string denoting the credit_amount field in the database.
	FieldCreditAmount = "credit_amount"
	// FieldBalanceBefore holds the string denoting the balance_before field in the database.
	FieldBalanceBefore = "balance_before"
	// FieldBalanceAfter holds the string denoting the balance_after field in the database.
	FieldBalanceAfter = "balance_after"
	// FieldCreditBalanceBefore holds the string denoting the credit_balance_before field in the database.
	FieldCreditBalanceBefore = "credit_balance_before"
	// FieldCreditBalanceAfter holds the string denoting the credit_balance_after field in the database.
	FieldCreditBalanceAfter = "credit_balance_after"
	// FieldReferenceType holds the string denoting the reference_type field in the database.
	FieldReferenceType = "reference_type"
	// FieldReferenceID holds the string denoting the reference_id field in the database.
	FieldReferenceID = "reference_id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldTransactionStatus holds the string denoting the transaction_status field in the database.
	FieldTransactionStatus = "transaction_status"
	// FieldExpiryDate holds the string denoting the expiry_date field in the database.
	FieldExpiryDate = "expiry_date"
	// FieldCreditsAvailable holds the string denoting the credits_available field in the database.
	FieldCreditsAvailable = "credits_available"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldTransactionReason holds the string denoting the transaction_reason field in the database.
	FieldTransactionReason = "transaction_reason"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// Table holds the table name of the wallettransaction in the database.
	Table = "wallet_transactions"
)

// Columns holds all SQL columns for wallettransaction fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldEnvironmentID,
	FieldWalletID,
	FieldCustomerID,
	FieldType,
	FieldAmount,
	FieldCreditAmount,
	FieldBalanceBefore,
	FieldBalanceAfter,
	FieldCreditBalanceBefore,
	FieldCreditBalanceAfter,
	FieldReferenceType,
	FieldReferenceID,
	FieldDescription,
	FieldMetadata,
	FieldTransactionStatus,
	FieldExpiryDate,
	FieldCreditsAvailable,
	FieldCurrency,
	FieldIdempotencyKey,
	FieldTransactionReason,
	FieldPriority,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	TenantIDValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnvironmentID holds the default value on creation for the "environment_id" field.
	DefaultEnvironmentID string
	// WalletIDValidator is a validator for the "wallet_id" field. It is called by the builders before save.
	WalletIDValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType types.TransactionType
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultTransactionStatus holds the default value on creation for the "transaction_status" field.
	DefaultTransactionStatus types.TransactionStatus
	// DefaultTransactionReason holds the default value on creation for the "transaction_reason" field.
	DefaultTransactionReason types.TransactionReason
)

// OrderOption defines the ordering options for the WalletTransaction queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByEnvironmentID orders the results by the environment_id field.
func ByEnvironmentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironmentID, opts...).ToFunc()
}

// ByWalletID orders the results by the wallet_id field.
func ByWalletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletID, opts...).ToFunc()
}

// ByCustomerID orders the results by the customer_id field.
func ByCustomerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByCreditAmount orders the results by the credit_amount field.
func ByCreditAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditAmount, opts...).ToFunc()
}

// ByBalanceBefore orders the results by the balance_before field.
func ByBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceBefore, opts...).ToFunc()
}

// ByBalanceAfter orders the results by the balance_after field.
func ByBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAfter, opts...).ToFunc()
}

// ByCreditBalanceBefore orders the results by the credit_balance_before field.
func ByCreditBalanceBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditBalanceBefore, opts...).ToFunc()
}

// ByCreditBalanceAfter orders the results by the credit_balance_after field.
func ByCreditBalanceAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditBalanceAfter, opts...).ToFunc()
}

// ByReferenceType orders the results by the reference_type field.
func ByReferenceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceType, opts...).ToFunc()
}

// ByReferenceID orders the results by the reference_id field.
func ByReferenceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferenceID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByTransactionStatus orders the results by the transaction_status field.
func ByTransactionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionStatus, opts...).ToFunc()
}

// ByExpiryDate orders the results by the expiry_date field.
func ByExpiryDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiryDate, opts...).ToFunc()
}

// ByCreditsAvailable orders the results by the credits_available field.
func ByCreditsAvailable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreditsAvailable, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByTransactionReason orders the results by the transaction_reason field.
func ByTransactionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTransactionReason, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}
