// Code generated by ent, DO NOT EDIT.

package wallettransaction

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldTenantID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUpdatedBy, v))
}

// EnvironmentID applies equality check predicate on the "environment_id" field. It's identical to EnvironmentIDEQ.
func EnvironmentID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldEnvironmentID, v))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldWalletID, v))
}

// CustomerID applies equality check predicate on the "customer_id" field. It's identical to CustomerIDEQ.
func CustomerID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCustomerID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldType, vc))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldAmount, v))
}

// CreditAmount applies equality check predicate on the "credit_amount" field. It's identical to CreditAmountEQ.
func CreditAmount(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditAmount, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceAfter, v))
}

// CreditBalanceBefore applies equality check predicate on the "credit_balance_before" field. It's identical to CreditBalanceBeforeEQ.
func CreditBalanceBefore(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditBalanceBefore, v))
}

// CreditBalanceAfter applies equality check predicate on the "credit_balance_after" field. It's identical to CreditBalanceAfterEQ.
func CreditBalanceAfter(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditBalanceAfter, v))
}

// ReferenceType applies equality check predicate on the "reference_type" field. It's identical to ReferenceTypeEQ.
func ReferenceType(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceType, vc))
}

// ReferenceID applies equality check predicate on the "reference_id" field. It's identical to ReferenceIDEQ.
func ReferenceID(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldDescription, v))
}

// TransactionStatus applies equality check predicate on the "transaction_status" field. It's identical to TransactionStatusEQ.
func TransactionStatus(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldTransactionStatus, vc))
}

// ExpiryDate applies equality check predicate on the "expiry_date" field. It's identical to ExpiryDateEQ.
func ExpiryDate(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldExpiryDate, v))
}

// CreditsAvailable applies equality check predicate on the "credits_available" field. It's identical to CreditsAvailableEQ.
func CreditsAvailable(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditsAvailable, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCurrency, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// TransactionReason applies equality check predicate on the "transaction_reason" field. It's identical to TransactionReasonEQ.
func TransactionReason(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldTransactionReason, vc))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldPriority, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldTenantID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldUpdatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// EnvironmentIDEQ applies the EQ predicate on the "environment_id" field.
func EnvironmentIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldEnvironmentID, v))
}

// EnvironmentIDNEQ applies the NEQ predicate on the "environment_id" field.
func EnvironmentIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldEnvironmentID, v))
}

// EnvironmentIDIn applies the In predicate on the "environment_id" field.
func EnvironmentIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDNotIn applies the NotIn predicate on the "environment_id" field.
func EnvironmentIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldEnvironmentID, vs...))
}

// EnvironmentIDGT applies the GT predicate on the "environment_id" field.
func EnvironmentIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldEnvironmentID, v))
}

// EnvironmentIDGTE applies the GTE predicate on the "environment_id" field.
func EnvironmentIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldEnvironmentID, v))
}

// EnvironmentIDLT applies the LT predicate on the "environment_id" field.
func EnvironmentIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldEnvironmentID, v))
}

// EnvironmentIDLTE applies the LTE predicate on the "environment_id" field.
func EnvironmentIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldEnvironmentID, v))
}

// EnvironmentIDContains applies the Contains predicate on the "environment_id" field.
func EnvironmentIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldEnvironmentID, v))
}

// EnvironmentIDHasPrefix applies the HasPrefix predicate on the "environment_id" field.
func EnvironmentIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldEnvironmentID, v))
}

// EnvironmentIDHasSuffix applies the HasSuffix predicate on the "environment_id" field.
func EnvironmentIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldEnvironmentID, v))
}

// EnvironmentIDIsNil applies the IsNil predicate on the "environment_id" field.
func EnvironmentIDIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldEnvironmentID))
}

// EnvironmentIDNotNil applies the NotNil predicate on the "environment_id" field.
func EnvironmentIDNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldEnvironmentID))
}

// EnvironmentIDEqualFold applies the EqualFold predicate on the "environment_id" field.
func EnvironmentIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldEnvironmentID, v))
}

// EnvironmentIDContainsFold applies the ContainsFold predicate on the "environment_id" field.
func EnvironmentIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldEnvironmentID, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldWalletID, vs...))
}

// WalletIDGT applies the GT predicate on the "wallet_id" field.
func WalletIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldWalletID, v))
}

// WalletIDGTE applies the GTE predicate on the "wallet_id" field.
func WalletIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldWalletID, v))
}

// WalletIDLT applies the LT predicate on the "wallet_id" field.
func WalletIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldWalletID, v))
}

// WalletIDLTE applies the LTE predicate on the "wallet_id" field.
func WalletIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldWalletID, v))
}

// WalletIDContains applies the Contains predicate on the "wallet_id" field.
func WalletIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldWalletID, v))
}

// WalletIDHasPrefix applies the HasPrefix predicate on the "wallet_id" field.
func WalletIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldWalletID, v))
}

// WalletIDHasSuffix applies the HasSuffix predicate on the "wallet_id" field.
func WalletIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldWalletID, v))
}

// WalletIDEqualFold applies the EqualFold predicate on the "wallet_id" field.
func WalletIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldWalletID, v))
}

// WalletIDContainsFold applies the ContainsFold predicate on the "wallet_id" field.
func WalletIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldWalletID, v))
}

// CustomerIDEQ applies the EQ predicate on the "customer_id" field.
func CustomerIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCustomerID, v))
}

// CustomerIDNEQ applies the NEQ predicate on the "customer_id" field.
func CustomerIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCustomerID, v))
}

// CustomerIDIn applies the In predicate on the "customer_id" field.
func CustomerIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCustomerID, vs...))
}

// CustomerIDNotIn applies the NotIn predicate on the "customer_id" field.
func CustomerIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCustomerID, vs...))
}

// CustomerIDGT applies the GT predicate on the "customer_id" field.
func CustomerIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCustomerID, v))
}

// CustomerIDGTE applies the GTE predicate on the "customer_id" field.
func CustomerIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCustomerID, v))
}

// CustomerIDLT applies the LT predicate on the "customer_id" field.
func CustomerIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCustomerID, v))
}

// CustomerIDLTE applies the LTE predicate on the "customer_id" field.
func CustomerIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCustomerID, v))
}

// CustomerIDContains applies the Contains predicate on the "customer_id" field.
func CustomerIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldCustomerID, v))
}

// CustomerIDHasPrefix applies the HasPrefix predicate on the "customer_id" field.
func CustomerIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldCustomerID, v))
}

// CustomerIDHasSuffix applies the HasSuffix predicate on the "customer_id" field.
func CustomerIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldCustomerID, v))
}

// CustomerIDIsNil applies the IsNil predicate on the "customer_id" field.
func CustomerIDIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldCustomerID))
}

// CustomerIDNotNil applies the NotNil predicate on the "customer_id" field.
func CustomerIDNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldCustomerID))
}

// CustomerIDEqualFold applies the EqualFold predicate on the "customer_id" field.
func CustomerIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldCustomerID, v))
}

// CustomerIDContainsFold applies the ContainsFold predicate on the "customer_id" field.
func CustomerIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldCustomerID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...types.TransactionType) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...types.TransactionType) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldNotIn(FieldType, v...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGT(FieldType, vc))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGTE(FieldType, vc))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLT(FieldType, vc))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLTE(FieldType, vc))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContains(FieldType, vc))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldType, vc))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldType, vc))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldType, vc))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v types.TransactionType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldType, vc))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldAmount, v))
}

// CreditAmountEQ applies the EQ predicate on the "credit_amount" field.
func CreditAmountEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditAmount, v))
}

// CreditAmountNEQ applies the NEQ predicate on the "credit_amount" field.
func CreditAmountNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreditAmount, v))
}

// CreditAmountIn applies the In predicate on the "credit_amount" field.
func CreditAmountIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreditAmount, vs...))
}

// CreditAmountNotIn applies the NotIn predicate on the "credit_amount" field.
func CreditAmountNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreditAmount, vs...))
}

// CreditAmountGT applies the GT predicate on the "credit_amount" field.
func CreditAmountGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreditAmount, v))
}

// CreditAmountGTE applies the GTE predicate on the "credit_amount" field.
func CreditAmountGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreditAmount, v))
}

// CreditAmountLT applies the LT predicate on the "credit_amount" field.
func CreditAmountLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreditAmount, v))
}

// CreditAmountLTE applies the LTE predicate on the "credit_amount" field.
func CreditAmountLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreditAmount, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldBalanceAfter, v))
}

// CreditBalanceBeforeEQ applies the EQ predicate on the "credit_balance_before" field.
func CreditBalanceBeforeEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditBalanceBefore, v))
}

// CreditBalanceBeforeNEQ applies the NEQ predicate on the "credit_balance_before" field.
func CreditBalanceBeforeNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreditBalanceBefore, v))
}

// CreditBalanceBeforeIn applies the In predicate on the "credit_balance_before" field.
func CreditBalanceBeforeIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreditBalanceBefore, vs...))
}

// CreditBalanceBeforeNotIn applies the NotIn predicate on the "credit_balance_before" field.
func CreditBalanceBeforeNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreditBalanceBefore, vs...))
}

// CreditBalanceBeforeGT applies the GT predicate on the "credit_balance_before" field.
func CreditBalanceBeforeGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreditBalanceBefore, v))
}

// CreditBalanceBeforeGTE applies the GTE predicate on the "credit_balance_before" field.
func CreditBalanceBeforeGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreditBalanceBefore, v))
}

// CreditBalanceBeforeLT applies the LT predicate on the "credit_balance_before" field.
func CreditBalanceBeforeLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreditBalanceBefore, v))
}

// CreditBalanceBeforeLTE applies the LTE predicate on the "credit_balance_before" field.
func CreditBalanceBeforeLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreditBalanceBefore, v))
}

// CreditBalanceAfterEQ applies the EQ predicate on the "credit_balance_after" field.
func CreditBalanceAfterEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditBalanceAfter, v))
}

// CreditBalanceAfterNEQ applies the NEQ predicate on the "credit_balance_after" field.
func CreditBalanceAfterNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreditBalanceAfter, v))
}

// CreditBalanceAfterIn applies the In predicate on the "credit_balance_after" field.
func CreditBalanceAfterIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreditBalanceAfter, vs...))
}

// CreditBalanceAfterNotIn applies the NotIn predicate on the "credit_balance_after" field.
func CreditBalanceAfterNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreditBalanceAfter, vs...))
}

// CreditBalanceAfterGT applies the GT predicate on the "credit_balance_after" field.
func CreditBalanceAfterGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreditBalanceAfter, v))
}

// CreditBalanceAfterGTE applies the GTE predicate on the "credit_balance_after" field.
func CreditBalanceAfterGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreditBalanceAfter, v))
}

// CreditBalanceAfterLT applies the LT predicate on the "credit_balance_after" field.
func CreditBalanceAfterLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreditBalanceAfter, v))
}

// CreditBalanceAfterLTE applies the LTE predicate on the "credit_balance_after" field.
func CreditBalanceAfterLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreditBalanceAfter, v))
}

// ReferenceTypeEQ applies the EQ predicate on the "reference_type" field.
func ReferenceTypeEQ(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceType, vc))
}

// ReferenceTypeNEQ applies the NEQ predicate on the "reference_type" field.
func ReferenceTypeNEQ(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldNEQ(FieldReferenceType, vc))
}

// ReferenceTypeIn applies the In predicate on the "reference_type" field.
func ReferenceTypeIn(vs ...types.WalletTxReferenceType) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldIn(FieldReferenceType, v...))
}

// ReferenceTypeNotIn applies the NotIn predicate on the "reference_type" field.
func ReferenceTypeNotIn(vs ...types.WalletTxReferenceType) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldNotIn(FieldReferenceType, v...))
}

// ReferenceTypeGT applies the GT predicate on the "reference_type" field.
func ReferenceTypeGT(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGT(FieldReferenceType, vc))
}

// ReferenceTypeGTE applies the GTE predicate on the "reference_type" field.
func ReferenceTypeGTE(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGTE(FieldReferenceType, vc))
}

// ReferenceTypeLT applies the LT predicate on the "reference_type" field.
func ReferenceTypeLT(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLT(FieldReferenceType, vc))
}

// ReferenceTypeLTE applies the LTE predicate on the "reference_type" field.
func ReferenceTypeLTE(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLTE(FieldReferenceType, vc))
}

// ReferenceTypeContains applies the Contains predicate on the "reference_type" field.
func ReferenceTypeContains(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContains(FieldReferenceType, vc))
}

// ReferenceTypeHasPrefix applies the HasPrefix predicate on the "reference_type" field.
func ReferenceTypeHasPrefix(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldReferenceType, vc))
}

// ReferenceTypeHasSuffix applies the HasSuffix predicate on the "reference_type" field.
func ReferenceTypeHasSuffix(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldReferenceType, vc))
}

// ReferenceTypeIsNil applies the IsNil predicate on the "reference_type" field.
func ReferenceTypeIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldReferenceType))
}

// ReferenceTypeNotNil applies the NotNil predicate on the "reference_type" field.
func ReferenceTypeNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldReferenceType))
}

// ReferenceTypeEqualFold applies the EqualFold predicate on the "reference_type" field.
func ReferenceTypeEqualFold(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldReferenceType, vc))
}

// ReferenceTypeContainsFold applies the ContainsFold predicate on the "reference_type" field.
func ReferenceTypeContainsFold(v types.WalletTxReferenceType) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldReferenceType, vc))
}

// ReferenceIDEQ applies the EQ predicate on the "reference_id" field.
func ReferenceIDEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldReferenceID, v))
}

// ReferenceIDNEQ applies the NEQ predicate on the "reference_id" field.
func ReferenceIDNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldReferenceID, v))
}

// ReferenceIDIn applies the In predicate on the "reference_id" field.
func ReferenceIDIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldReferenceID, vs...))
}

// ReferenceIDNotIn applies the NotIn predicate on the "reference_id" field.
func ReferenceIDNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldReferenceID, vs...))
}

// ReferenceIDGT applies the GT predicate on the "reference_id" field.
func ReferenceIDGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldReferenceID, v))
}

// ReferenceIDGTE applies the GTE predicate on the "reference_id" field.
func ReferenceIDGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldReferenceID, v))
}

// ReferenceIDLT applies the LT predicate on the "reference_id" field.
func ReferenceIDLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldReferenceID, v))
}

// ReferenceIDLTE applies the LTE predicate on the "reference_id" field.
func ReferenceIDLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldReferenceID, v))
}

// ReferenceIDContains applies the Contains predicate on the "reference_id" field.
func ReferenceIDContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldReferenceID, v))
}

// ReferenceIDHasPrefix applies the HasPrefix predicate on the "reference_id" field.
func ReferenceIDHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldReferenceID, v))
}

// ReferenceIDHasSuffix applies the HasSuffix predicate on the "reference_id" field.
func ReferenceIDHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldReferenceID, v))
}

// ReferenceIDIsNil applies the IsNil predicate on the "reference_id" field.
func ReferenceIDIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldReferenceID))
}

// ReferenceIDNotNil applies the NotNil predicate on the "reference_id" field.
func ReferenceIDNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldReferenceID))
}

// ReferenceIDEqualFold applies the EqualFold predicate on the "reference_id" field.
func ReferenceIDEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldReferenceID, v))
}

// ReferenceIDContainsFold applies the ContainsFold predicate on the "reference_id" field.
func ReferenceIDContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldReferenceID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldDescription, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldMetadata))
}

// TransactionStatusEQ applies the EQ predicate on the "transaction_status" field.
func TransactionStatusEQ(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldTransactionStatus, vc))
}

// TransactionStatusNEQ applies the NEQ predicate on the "transaction_status" field.
func TransactionStatusNEQ(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldNEQ(FieldTransactionStatus, vc))
}

// TransactionStatusIn applies the In predicate on the "transaction_status" field.
func TransactionStatusIn(vs ...types.TransactionStatus) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldIn(FieldTransactionStatus, v...))
}

// TransactionStatusNotIn applies the NotIn predicate on the "transaction_status" field.
func TransactionStatusNotIn(vs ...types.TransactionStatus) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldNotIn(FieldTransactionStatus, v...))
}

// TransactionStatusGT applies the GT predicate on the "transaction_status" field.
func TransactionStatusGT(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGT(FieldTransactionStatus, vc))
}

// TransactionStatusGTE applies the GTE predicate on the "transaction_status" field.
func TransactionStatusGTE(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGTE(FieldTransactionStatus, vc))
}

// TransactionStatusLT applies the LT predicate on the "transaction_status" field.
func TransactionStatusLT(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLT(FieldTransactionStatus, vc))
}

// TransactionStatusLTE applies the LTE predicate on the "transaction_status" field.
func TransactionStatusLTE(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLTE(FieldTransactionStatus, vc))
}

// TransactionStatusContains applies the Contains predicate on the "transaction_status" field.
func TransactionStatusContains(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContains(FieldTransactionStatus, vc))
}

// TransactionStatusHasPrefix applies the HasPrefix predicate on the "transaction_status" field.
func TransactionStatusHasPrefix(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldTransactionStatus, vc))
}

// TransactionStatusHasSuffix applies the HasSuffix predicate on the "transaction_status" field.
func TransactionStatusHasSuffix(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldTransactionStatus, vc))
}

// TransactionStatusEqualFold applies the EqualFold predicate on the "transaction_status" field.
func TransactionStatusEqualFold(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldTransactionStatus, vc))
}

// TransactionStatusContainsFold applies the ContainsFold predicate on the "transaction_status" field.
func TransactionStatusContainsFold(v types.TransactionStatus) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldTransactionStatus, vc))
}

// ExpiryDateEQ applies the EQ predicate on the "expiry_date" field.
func ExpiryDateEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldExpiryDate, v))
}

// ExpiryDateNEQ applies the NEQ predicate on the "expiry_date" field.
func ExpiryDateNEQ(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldExpiryDate, v))
}

// ExpiryDateIn applies the In predicate on the "expiry_date" field.
func ExpiryDateIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldExpiryDate, vs...))
}

// ExpiryDateNotIn applies the NotIn predicate on the "expiry_date" field.
func ExpiryDateNotIn(vs ...time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldExpiryDate, vs...))
}

// ExpiryDateGT applies the GT predicate on the "expiry_date" field.
func ExpiryDateGT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldExpiryDate, v))
}

// ExpiryDateGTE applies the GTE predicate on the "expiry_date" field.
func ExpiryDateGTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldExpiryDate, v))
}

// ExpiryDateLT applies the LT predicate on the "expiry_date" field.
func ExpiryDateLT(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldExpiryDate, v))
}

// ExpiryDateLTE applies the LTE predicate on the "expiry_date" field.
func ExpiryDateLTE(v time.Time) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldExpiryDate, v))
}

// ExpiryDateIsNil applies the IsNil predicate on the "expiry_date" field.
func ExpiryDateIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldExpiryDate))
}

// ExpiryDateNotNil applies the NotNil predicate on the "expiry_date" field.
func ExpiryDateNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldExpiryDate))
}

// CreditsAvailableEQ applies the EQ predicate on the "credits_available" field.
func CreditsAvailableEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCreditsAvailable, v))
}

// CreditsAvailableNEQ applies the NEQ predicate on the "credits_available" field.
func CreditsAvailableNEQ(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCreditsAvailable, v))
}

// CreditsAvailableIn applies the In predicate on the "credits_available" field.
func CreditsAvailableIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCreditsAvailable, vs...))
}

// CreditsAvailableNotIn applies the NotIn predicate on the "credits_available" field.
func CreditsAvailableNotIn(vs ...decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCreditsAvailable, vs...))
}

// CreditsAvailableGT applies the GT predicate on the "credits_available" field.
func CreditsAvailableGT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCreditsAvailable, v))
}

// CreditsAvailableGTE applies the GTE predicate on the "credits_available" field.
func CreditsAvailableGTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCreditsAvailable, v))
}

// CreditsAvailableLT applies the LT predicate on the "credits_available" field.
func CreditsAvailableLT(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCreditsAvailable, v))
}

// CreditsAvailableLTE applies the LTE predicate on the "credits_available" field.
func CreditsAvailableLTE(v decimal.Decimal) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCreditsAvailable, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyIsNil applies the IsNil predicate on the "currency" field.
func CurrencyIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldCurrency))
}

// CurrencyNotNil applies the NotNil predicate on the "currency" field.
func CurrencyNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldCurrency))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldCurrency, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// TransactionReasonEQ applies the EQ predicate on the "transaction_reason" field.
func TransactionReasonEQ(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEQ(FieldTransactionReason, vc))
}

// TransactionReasonNEQ applies the NEQ predicate on the "transaction_reason" field.
func TransactionReasonNEQ(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldNEQ(FieldTransactionReason, vc))
}

// TransactionReasonIn applies the In predicate on the "transaction_reason" field.
func TransactionReasonIn(vs ...types.TransactionReason) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldIn(FieldTransactionReason, v...))
}

// TransactionReasonNotIn applies the NotIn predicate on the "transaction_reason" field.
func TransactionReasonNotIn(vs ...types.TransactionReason) predicate.WalletTransaction {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.WalletTransaction(sql.FieldNotIn(FieldTransactionReason, v...))
}

// TransactionReasonGT applies the GT predicate on the "transaction_reason" field.
func TransactionReasonGT(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGT(FieldTransactionReason, vc))
}

// TransactionReasonGTE applies the GTE predicate on the "transaction_reason" field.
func TransactionReasonGTE(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldGTE(FieldTransactionReason, vc))
}

// TransactionReasonLT applies the LT predicate on the "transaction_reason" field.
func TransactionReasonLT(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLT(FieldTransactionReason, vc))
}

// TransactionReasonLTE applies the LTE predicate on the "transaction_reason" field.
func TransactionReasonLTE(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldLTE(FieldTransactionReason, vc))
}

// TransactionReasonContains applies the Contains predicate on the "transaction_reason" field.
func TransactionReasonContains(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContains(FieldTransactionReason, vc))
}

// TransactionReasonHasPrefix applies the HasPrefix predicate on the "transaction_reason" field.
func TransactionReasonHasPrefix(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasPrefix(FieldTransactionReason, vc))
}

// TransactionReasonHasSuffix applies the HasSuffix predicate on the "transaction_reason" field.
func TransactionReasonHasSuffix(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldHasSuffix(FieldTransactionReason, vc))
}

// TransactionReasonEqualFold applies the EqualFold predicate on the "transaction_reason" field.
func TransactionReasonEqualFold(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldEqualFold(FieldTransactionReason, vc))
}

// TransactionReasonContainsFold applies the ContainsFold predicate on the "transaction_reason" field.
func TransactionReasonContainsFold(v types.TransactionReason) predicate.WalletTransaction {
	vc := string(v)
	return predicate.WalletTransaction(sql.FieldContainsFold(FieldTransactionReason, vc))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldLTE(FieldPriority, v))
}

// PriorityIsNil applies the IsNil predicate on the "priority" field.
func PriorityIsNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldIsNull(FieldPriority))
}

// PriorityNotNil applies the NotNil predicate on the "priority" field.
func PriorityNotNil() predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.FieldNotNull(FieldPriority))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WalletTransaction) predicate.WalletTransaction {
	return predicate.WalletTransaction(sql.NotPredicates(p))
}
