// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/couponapplication"
	"github.com/flexprice/flexprice/ent/couponassociation"
	"github.com/flexprice/flexprice/ent/creditgrant"
	"github.com/flexprice/flexprice/ent/customer"
	"github.com/flexprice/flexprice/ent/predicate"
	"github.com/flexprice/flexprice/ent/subscription"
	"github.com/flexprice/flexprice/ent/subscriptionlineitem"
	"github.com/flexprice/flexprice/ent/subscriptionpause"
	"github.com/flexprice/flexprice/ent/subscriptionphase"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (su *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetStatus sets the "status" field.
func (su *SubscriptionUpdate) SetStatus(s string) *SubscriptionUpdate {
	su.mutation.SetStatus(s)
	return su
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableStatus(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetStatus(*s)
	}
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *SubscriptionUpdate) SetUpdatedAt(t time.Time) *SubscriptionUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// SetUpdatedBy sets the "updated_by" field.
func (su *SubscriptionUpdate) SetUpdatedBy(s string) *SubscriptionUpdate {
	su.mutation.SetUpdatedBy(s)
	return su
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableUpdatedBy(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetUpdatedBy(*s)
	}
	return su
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (su *SubscriptionUpdate) ClearUpdatedBy() *SubscriptionUpdate {
	su.mutation.ClearUpdatedBy()
	return su
}

// SetLookupKey sets the "lookup_key" field.
func (su *SubscriptionUpdate) SetLookupKey(s string) *SubscriptionUpdate {
	su.mutation.SetLookupKey(s)
	return su
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableLookupKey(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetLookupKey(*s)
	}
	return su
}

// ClearLookupKey clears the value of the "lookup_key" field.
func (su *SubscriptionUpdate) ClearLookupKey() *SubscriptionUpdate {
	su.mutation.ClearLookupKey()
	return su
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (su *SubscriptionUpdate) SetSubscriptionStatus(ts types.SubscriptionStatus) *SubscriptionUpdate {
	su.mutation.SetSubscriptionStatus(ts)
	return su
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableSubscriptionStatus(ts *types.SubscriptionStatus) *SubscriptionUpdate {
	if ts != nil {
		su.SetSubscriptionStatus(*ts)
	}
	return su
}

// SetBillingAnchor sets the "billing_anchor" field.
func (su *SubscriptionUpdate) SetBillingAnchor(t time.Time) *SubscriptionUpdate {
	su.mutation.SetBillingAnchor(t)
	return su
}

// SetNillableBillingAnchor sets the "billing_anchor" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableBillingAnchor(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetBillingAnchor(*t)
	}
	return su
}

// SetStartDate sets the "start_date" field.
func (su *SubscriptionUpdate) SetStartDate(t time.Time) *SubscriptionUpdate {
	su.mutation.SetStartDate(t)
	return su
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableStartDate(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetStartDate(*t)
	}
	return su
}

// SetEndDate sets the "end_date" field.
func (su *SubscriptionUpdate) SetEndDate(t time.Time) *SubscriptionUpdate {
	su.mutation.SetEndDate(t)
	return su
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableEndDate(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetEndDate(*t)
	}
	return su
}

// ClearEndDate clears the value of the "end_date" field.
func (su *SubscriptionUpdate) ClearEndDate() *SubscriptionUpdate {
	su.mutation.ClearEndDate()
	return su
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (su *SubscriptionUpdate) SetCurrentPeriodStart(t time.Time) *SubscriptionUpdate {
	su.mutation.SetCurrentPeriodStart(t)
	return su
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCurrentPeriodStart(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetCurrentPeriodStart(*t)
	}
	return su
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (su *SubscriptionUpdate) SetCurrentPeriodEnd(t time.Time) *SubscriptionUpdate {
	su.mutation.SetCurrentPeriodEnd(t)
	return su
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCurrentPeriodEnd(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetCurrentPeriodEnd(*t)
	}
	return su
}

// SetCancelledAt sets the "cancelled_at" field.
func (su *SubscriptionUpdate) SetCancelledAt(t time.Time) *SubscriptionUpdate {
	su.mutation.SetCancelledAt(t)
	return su
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCancelledAt(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetCancelledAt(*t)
	}
	return su
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (su *SubscriptionUpdate) ClearCancelledAt() *SubscriptionUpdate {
	su.mutation.ClearCancelledAt()
	return su
}

// SetCancelAt sets the "cancel_at" field.
func (su *SubscriptionUpdate) SetCancelAt(t time.Time) *SubscriptionUpdate {
	su.mutation.SetCancelAt(t)
	return su
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCancelAt(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetCancelAt(*t)
	}
	return su
}

// ClearCancelAt clears the value of the "cancel_at" field.
func (su *SubscriptionUpdate) ClearCancelAt() *SubscriptionUpdate {
	su.mutation.ClearCancelAt()
	return su
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (su *SubscriptionUpdate) SetCancelAtPeriodEnd(b bool) *SubscriptionUpdate {
	su.mutation.SetCancelAtPeriodEnd(b)
	return su
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCancelAtPeriodEnd(b *bool) *SubscriptionUpdate {
	if b != nil {
		su.SetCancelAtPeriodEnd(*b)
	}
	return su
}

// SetTrialStart sets the "trial_start" field.
func (su *SubscriptionUpdate) SetTrialStart(t time.Time) *SubscriptionUpdate {
	su.mutation.SetTrialStart(t)
	return su
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableTrialStart(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetTrialStart(*t)
	}
	return su
}

// ClearTrialStart clears the value of the "trial_start" field.
func (su *SubscriptionUpdate) ClearTrialStart() *SubscriptionUpdate {
	su.mutation.ClearTrialStart()
	return su
}

// SetTrialEnd sets the "trial_end" field.
func (su *SubscriptionUpdate) SetTrialEnd(t time.Time) *SubscriptionUpdate {
	su.mutation.SetTrialEnd(t)
	return su
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableTrialEnd(t *time.Time) *SubscriptionUpdate {
	if t != nil {
		su.SetTrialEnd(*t)
	}
	return su
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (su *SubscriptionUpdate) ClearTrialEnd() *SubscriptionUpdate {
	su.mutation.ClearTrialEnd()
	return su
}

// SetVersion sets the "version" field.
func (su *SubscriptionUpdate) SetVersion(i int) *SubscriptionUpdate {
	su.mutation.ResetVersion()
	su.mutation.SetVersion(i)
	return su
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableVersion(i *int) *SubscriptionUpdate {
	if i != nil {
		su.SetVersion(*i)
	}
	return su
}

// AddVersion adds i to the "version" field.
func (su *SubscriptionUpdate) AddVersion(i int) *SubscriptionUpdate {
	su.mutation.AddVersion(i)
	return su
}

// SetMetadata sets the "metadata" field.
func (su *SubscriptionUpdate) SetMetadata(m map[string]string) *SubscriptionUpdate {
	su.mutation.SetMetadata(m)
	return su
}

// ClearMetadata clears the value of the "metadata" field.
func (su *SubscriptionUpdate) ClearMetadata() *SubscriptionUpdate {
	su.mutation.ClearMetadata()
	return su
}

// SetPauseStatus sets the "pause_status" field.
func (su *SubscriptionUpdate) SetPauseStatus(ts types.PauseStatus) *SubscriptionUpdate {
	su.mutation.SetPauseStatus(ts)
	return su
}

// SetNillablePauseStatus sets the "pause_status" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillablePauseStatus(ts *types.PauseStatus) *SubscriptionUpdate {
	if ts != nil {
		su.SetPauseStatus(*ts)
	}
	return su
}

// SetActivePauseID sets the "active_pause_id" field.
func (su *SubscriptionUpdate) SetActivePauseID(s string) *SubscriptionUpdate {
	su.mutation.SetActivePauseID(s)
	return su
}

// SetNillableActivePauseID sets the "active_pause_id" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableActivePauseID(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetActivePauseID(*s)
	}
	return su
}

// ClearActivePauseID clears the value of the "active_pause_id" field.
func (su *SubscriptionUpdate) ClearActivePauseID() *SubscriptionUpdate {
	su.mutation.ClearActivePauseID()
	return su
}

// SetCommitmentAmount sets the "commitment_amount" field.
func (su *SubscriptionUpdate) SetCommitmentAmount(d decimal.Decimal) *SubscriptionUpdate {
	su.mutation.SetCommitmentAmount(d)
	return su
}

// SetNillableCommitmentAmount sets the "commitment_amount" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCommitmentAmount(d *decimal.Decimal) *SubscriptionUpdate {
	if d != nil {
		su.SetCommitmentAmount(*d)
	}
	return su
}

// ClearCommitmentAmount clears the value of the "commitment_amount" field.
func (su *SubscriptionUpdate) ClearCommitmentAmount() *SubscriptionUpdate {
	su.mutation.ClearCommitmentAmount()
	return su
}

// SetOverageFactor sets the "overage_factor" field.
func (su *SubscriptionUpdate) SetOverageFactor(d decimal.Decimal) *SubscriptionUpdate {
	su.mutation.SetOverageFactor(d)
	return su
}

// SetNillableOverageFactor sets the "overage_factor" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableOverageFactor(d *decimal.Decimal) *SubscriptionUpdate {
	if d != nil {
		su.SetOverageFactor(*d)
	}
	return su
}

// ClearOverageFactor clears the value of the "overage_factor" field.
func (su *SubscriptionUpdate) ClearOverageFactor() *SubscriptionUpdate {
	su.mutation.ClearOverageFactor()
	return su
}

// SetPaymentBehavior sets the "payment_behavior" field.
func (su *SubscriptionUpdate) SetPaymentBehavior(tb types.PaymentBehavior) *SubscriptionUpdate {
	su.mutation.SetPaymentBehavior(tb)
	return su
}

// SetNillablePaymentBehavior sets the "payment_behavior" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillablePaymentBehavior(tb *types.PaymentBehavior) *SubscriptionUpdate {
	if tb != nil {
		su.SetPaymentBehavior(*tb)
	}
	return su
}

// SetCollectionMethod sets the "collection_method" field.
func (su *SubscriptionUpdate) SetCollectionMethod(tm types.CollectionMethod) *SubscriptionUpdate {
	su.mutation.SetCollectionMethod(tm)
	return su
}

// SetNillableCollectionMethod sets the "collection_method" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCollectionMethod(tm *types.CollectionMethod) *SubscriptionUpdate {
	if tm != nil {
		su.SetCollectionMethod(*tm)
	}
	return su
}

// SetGatewayPaymentMethodID sets the "gateway_payment_method_id" field.
func (su *SubscriptionUpdate) SetGatewayPaymentMethodID(s string) *SubscriptionUpdate {
	su.mutation.SetGatewayPaymentMethodID(s)
	return su
}

// SetNillableGatewayPaymentMethodID sets the "gateway_payment_method_id" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableGatewayPaymentMethodID(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetGatewayPaymentMethodID(*s)
	}
	return su
}

// ClearGatewayPaymentMethodID clears the value of the "gateway_payment_method_id" field.
func (su *SubscriptionUpdate) ClearGatewayPaymentMethodID() *SubscriptionUpdate {
	su.mutation.ClearGatewayPaymentMethodID()
	return su
}

// SetInvoiceCadence sets the "invoice_cadence" field.
func (su *SubscriptionUpdate) SetInvoiceCadence(tc types.InvoiceCadence) *SubscriptionUpdate {
	su.mutation.SetInvoiceCadence(tc)
	return su
}

// SetNillableInvoiceCadence sets the "invoice_cadence" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableInvoiceCadence(tc *types.InvoiceCadence) *SubscriptionUpdate {
	if tc != nil {
		su.SetInvoiceCadence(*tc)
	}
	return su
}

// SetCustomerTimezone sets the "customer_timezone" field.
func (su *SubscriptionUpdate) SetCustomerTimezone(s string) *SubscriptionUpdate {
	su.mutation.SetCustomerTimezone(s)
	return su
}

// SetNillableCustomerTimezone sets the "customer_timezone" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableCustomerTimezone(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetCustomerTimezone(*s)
	}
	return su
}

// SetEnableTrueUp sets the "enable_true_up" field.
func (su *SubscriptionUpdate) SetEnableTrueUp(b bool) *SubscriptionUpdate {
	su.mutation.SetEnableTrueUp(b)
	return su
}

// SetNillableEnableTrueUp sets the "enable_true_up" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableEnableTrueUp(b *bool) *SubscriptionUpdate {
	if b != nil {
		su.SetEnableTrueUp(*b)
	}
	return su
}

// SetInvoicingCustomerID sets the "invoicing_customer_id" field.
func (su *SubscriptionUpdate) SetInvoicingCustomerID(s string) *SubscriptionUpdate {
	su.mutation.SetInvoicingCustomerID(s)
	return su
}

// SetNillableInvoicingCustomerID sets the "invoicing_customer_id" field if the given value is not nil.
func (su *SubscriptionUpdate) SetNillableInvoicingCustomerID(s *string) *SubscriptionUpdate {
	if s != nil {
		su.SetInvoicingCustomerID(*s)
	}
	return su
}

// ClearInvoicingCustomerID clears the value of the "invoicing_customer_id" field.
func (su *SubscriptionUpdate) ClearInvoicingCustomerID() *SubscriptionUpdate {
	su.mutation.ClearInvoicingCustomerID()
	return su
}

// AddLineItemIDs adds the "line_items" edge to the SubscriptionLineItem entity by IDs.
func (su *SubscriptionUpdate) AddLineItemIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddLineItemIDs(ids...)
	return su
}

// AddLineItems adds the "line_items" edges to the SubscriptionLineItem entity.
func (su *SubscriptionUpdate) AddLineItems(s ...*SubscriptionLineItem) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddLineItemIDs(ids...)
}

// AddPauseIDs adds the "pauses" edge to the SubscriptionPause entity by IDs.
func (su *SubscriptionUpdate) AddPauseIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddPauseIDs(ids...)
	return su
}

// AddPauses adds the "pauses" edges to the SubscriptionPause entity.
func (su *SubscriptionUpdate) AddPauses(s ...*SubscriptionPause) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddPauseIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the SubscriptionPhase entity by IDs.
func (su *SubscriptionUpdate) AddPhaseIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddPhaseIDs(ids...)
	return su
}

// AddPhases adds the "phases" edges to the SubscriptionPhase entity.
func (su *SubscriptionUpdate) AddPhases(s ...*SubscriptionPhase) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddPhaseIDs(ids...)
}

// AddCreditGrantIDs adds the "credit_grants" edge to the CreditGrant entity by IDs.
func (su *SubscriptionUpdate) AddCreditGrantIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddCreditGrantIDs(ids...)
	return su
}

// AddCreditGrants adds the "credit_grants" edges to the CreditGrant entity.
func (su *SubscriptionUpdate) AddCreditGrants(c ...*CreditGrant) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.AddCreditGrantIDs(ids...)
}

// AddCouponAssociationIDs adds the "coupon_associations" edge to the CouponAssociation entity by IDs.
func (su *SubscriptionUpdate) AddCouponAssociationIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddCouponAssociationIDs(ids...)
	return su
}

// AddCouponAssociations adds the "coupon_associations" edges to the CouponAssociation entity.
func (su *SubscriptionUpdate) AddCouponAssociations(c ...*CouponAssociation) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.AddCouponAssociationIDs(ids...)
}

// AddCouponApplicationIDs adds the "coupon_applications" edge to the CouponApplication entity by IDs.
func (su *SubscriptionUpdate) AddCouponApplicationIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.AddCouponApplicationIDs(ids...)
	return su
}

// AddCouponApplications adds the "coupon_applications" edges to the CouponApplication entity.
func (su *SubscriptionUpdate) AddCouponApplications(c ...*CouponApplication) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.AddCouponApplicationIDs(ids...)
}

// SetInvoicingCustomer sets the "invoicing_customer" edge to the Customer entity.
func (su *SubscriptionUpdate) SetInvoicingCustomer(c *Customer) *SubscriptionUpdate {
	return su.SetInvoicingCustomerID(c.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (su *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return su.mutation
}

// ClearLineItems clears all "line_items" edges to the SubscriptionLineItem entity.
func (su *SubscriptionUpdate) ClearLineItems() *SubscriptionUpdate {
	su.mutation.ClearLineItems()
	return su
}

// RemoveLineItemIDs removes the "line_items" edge to SubscriptionLineItem entities by IDs.
func (su *SubscriptionUpdate) RemoveLineItemIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemoveLineItemIDs(ids...)
	return su
}

// RemoveLineItems removes "line_items" edges to SubscriptionLineItem entities.
func (su *SubscriptionUpdate) RemoveLineItems(s ...*SubscriptionLineItem) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveLineItemIDs(ids...)
}

// ClearPauses clears all "pauses" edges to the SubscriptionPause entity.
func (su *SubscriptionUpdate) ClearPauses() *SubscriptionUpdate {
	su.mutation.ClearPauses()
	return su
}

// RemovePauseIDs removes the "pauses" edge to SubscriptionPause entities by IDs.
func (su *SubscriptionUpdate) RemovePauseIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemovePauseIDs(ids...)
	return su
}

// RemovePauses removes "pauses" edges to SubscriptionPause entities.
func (su *SubscriptionUpdate) RemovePauses(s ...*SubscriptionPause) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemovePauseIDs(ids...)
}

// ClearPhases clears all "phases" edges to the SubscriptionPhase entity.
func (su *SubscriptionUpdate) ClearPhases() *SubscriptionUpdate {
	su.mutation.ClearPhases()
	return su
}

// RemovePhaseIDs removes the "phases" edge to SubscriptionPhase entities by IDs.
func (su *SubscriptionUpdate) RemovePhaseIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemovePhaseIDs(ids...)
	return su
}

// RemovePhases removes "phases" edges to SubscriptionPhase entities.
func (su *SubscriptionUpdate) RemovePhases(s ...*SubscriptionPhase) *SubscriptionUpdate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemovePhaseIDs(ids...)
}

// ClearCreditGrants clears all "credit_grants" edges to the CreditGrant entity.
func (su *SubscriptionUpdate) ClearCreditGrants() *SubscriptionUpdate {
	su.mutation.ClearCreditGrants()
	return su
}

// RemoveCreditGrantIDs removes the "credit_grants" edge to CreditGrant entities by IDs.
func (su *SubscriptionUpdate) RemoveCreditGrantIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemoveCreditGrantIDs(ids...)
	return su
}

// RemoveCreditGrants removes "credit_grants" edges to CreditGrant entities.
func (su *SubscriptionUpdate) RemoveCreditGrants(c ...*CreditGrant) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.RemoveCreditGrantIDs(ids...)
}

// ClearCouponAssociations clears all "coupon_associations" edges to the CouponAssociation entity.
func (su *SubscriptionUpdate) ClearCouponAssociations() *SubscriptionUpdate {
	su.mutation.ClearCouponAssociations()
	return su
}

// RemoveCouponAssociationIDs removes the "coupon_associations" edge to CouponAssociation entities by IDs.
func (su *SubscriptionUpdate) RemoveCouponAssociationIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemoveCouponAssociationIDs(ids...)
	return su
}

// RemoveCouponAssociations removes "coupon_associations" edges to CouponAssociation entities.
func (su *SubscriptionUpdate) RemoveCouponAssociations(c ...*CouponAssociation) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.RemoveCouponAssociationIDs(ids...)
}

// ClearCouponApplications clears all "coupon_applications" edges to the CouponApplication entity.
func (su *SubscriptionUpdate) ClearCouponApplications() *SubscriptionUpdate {
	su.mutation.ClearCouponApplications()
	return su
}

// RemoveCouponApplicationIDs removes the "coupon_applications" edge to CouponApplication entities by IDs.
func (su *SubscriptionUpdate) RemoveCouponApplicationIDs(ids ...string) *SubscriptionUpdate {
	su.mutation.RemoveCouponApplicationIDs(ids...)
	return su
}

// RemoveCouponApplications removes "coupon_applications" edges to CouponApplication entities.
func (su *SubscriptionUpdate) RemoveCouponApplications(c ...*CouponApplication) *SubscriptionUpdate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return su.RemoveCouponApplicationIDs(ids...)
}

// ClearInvoicingCustomer clears the "invoicing_customer" edge to the Customer entity.
func (su *SubscriptionUpdate) ClearInvoicingCustomer() *SubscriptionUpdate {
	su.mutation.ClearInvoicingCustomer()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	su.defaults()
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *SubscriptionUpdate) defaults() {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
}

func (su *SubscriptionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if su.mutation.CreatedByCleared() {
		_spec.ClearField(subscription.FieldCreatedBy, field.TypeString)
	}
	if value, ok := su.mutation.UpdatedBy(); ok {
		_spec.SetField(subscription.FieldUpdatedBy, field.TypeString, value)
	}
	if su.mutation.UpdatedByCleared() {
		_spec.ClearField(subscription.FieldUpdatedBy, field.TypeString)
	}
	if su.mutation.EnvironmentIDCleared() {
		_spec.ClearField(subscription.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := su.mutation.LookupKey(); ok {
		_spec.SetField(subscription.FieldLookupKey, field.TypeString, value)
	}
	if su.mutation.LookupKeyCleared() {
		_spec.ClearField(subscription.FieldLookupKey, field.TypeString)
	}
	if value, ok := su.mutation.SubscriptionStatus(); ok {
		_spec.SetField(subscription.FieldSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := su.mutation.BillingAnchor(); ok {
		_spec.SetField(subscription.FieldBillingAnchor, field.TypeTime, value)
	}
	if value, ok := su.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := su.mutation.EndDate(); ok {
		_spec.SetField(subscription.FieldEndDate, field.TypeTime, value)
	}
	if su.mutation.EndDateCleared() {
		_spec.ClearField(subscription.FieldEndDate, field.TypeTime)
	}
	if value, ok := su.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := su.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := su.mutation.CancelledAt(); ok {
		_spec.SetField(subscription.FieldCancelledAt, field.TypeTime, value)
	}
	if su.mutation.CancelledAtCleared() {
		_spec.ClearField(subscription.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := su.mutation.CancelAt(); ok {
		_spec.SetField(subscription.FieldCancelAt, field.TypeTime, value)
	}
	if su.mutation.CancelAtCleared() {
		_spec.ClearField(subscription.FieldCancelAt, field.TypeTime)
	}
	if value, ok := su.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := su.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
	}
	if su.mutation.TrialStartCleared() {
		_spec.ClearField(subscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := su.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if su.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := su.mutation.Version(); ok {
		_spec.SetField(subscription.FieldVersion, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedVersion(); ok {
		_spec.AddField(subscription.FieldVersion, field.TypeInt, value)
	}
	if value, ok := su.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
	}
	if su.mutation.MetadataCleared() {
		_spec.ClearField(subscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := su.mutation.PauseStatus(); ok {
		_spec.SetField(subscription.FieldPauseStatus, field.TypeString, value)
	}
	if value, ok := su.mutation.ActivePauseID(); ok {
		_spec.SetField(subscription.FieldActivePauseID, field.TypeString, value)
	}
	if su.mutation.ActivePauseIDCleared() {
		_spec.ClearField(subscription.FieldActivePauseID, field.TypeString)
	}
	if value, ok := su.mutation.CommitmentAmount(); ok {
		_spec.SetField(subscription.FieldCommitmentAmount, field.TypeOther, value)
	}
	if su.mutation.CommitmentAmountCleared() {
		_spec.ClearField(subscription.FieldCommitmentAmount, field.TypeOther)
	}
	if value, ok := su.mutation.OverageFactor(); ok {
		_spec.SetField(subscription.FieldOverageFactor, field.TypeOther, value)
	}
	if su.mutation.OverageFactorCleared() {
		_spec.ClearField(subscription.FieldOverageFactor, field.TypeOther)
	}
	if value, ok := su.mutation.PaymentBehavior(); ok {
		_spec.SetField(subscription.FieldPaymentBehavior, field.TypeString, value)
	}
	if value, ok := su.mutation.CollectionMethod(); ok {
		_spec.SetField(subscription.FieldCollectionMethod, field.TypeString, value)
	}
	if value, ok := su.mutation.GatewayPaymentMethodID(); ok {
		_spec.SetField(subscription.FieldGatewayPaymentMethodID, field.TypeString, value)
	}
	if su.mutation.GatewayPaymentMethodIDCleared() {
		_spec.ClearField(subscription.FieldGatewayPaymentMethodID, field.TypeString)
	}
	if value, ok := su.mutation.InvoiceCadence(); ok {
		_spec.SetField(subscription.FieldInvoiceCadence, field.TypeString, value)
	}
	if value, ok := su.mutation.CustomerTimezone(); ok {
		_spec.SetField(subscription.FieldCustomerTimezone, field.TypeString, value)
	}
	if value, ok := su.mutation.EnableTrueUp(); ok {
		_spec.SetField(subscription.FieldEnableTrueUp, field.TypeBool, value)
	}
	if su.mutation.LineItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedLineItemsIDs(); len(nodes) > 0 && !su.mutation.LineItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.LineItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PausesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPausesIDs(); len(nodes) > 0 && !su.mutation.PausesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PausesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !su.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.CreditGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedCreditGrantsIDs(); len(nodes) > 0 && !su.mutation.CreditGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.CreditGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.CouponAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedCouponAssociationsIDs(); len(nodes) > 0 && !su.mutation.CouponAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.CouponAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.CouponApplicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedCouponApplicationsIDs(); len(nodes) > 0 && !su.mutation.CouponApplicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.CouponApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.InvoicingCustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.InvoicingCustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetStatus sets the "status" field.
func (suo *SubscriptionUpdateOne) SetStatus(s string) *SubscriptionUpdateOne {
	suo.mutation.SetStatus(s)
	return suo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableStatus(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetStatus(*s)
	}
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *SubscriptionUpdateOne) SetUpdatedAt(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// SetUpdatedBy sets the "updated_by" field.
func (suo *SubscriptionUpdateOne) SetUpdatedBy(s string) *SubscriptionUpdateOne {
	suo.mutation.SetUpdatedBy(s)
	return suo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableUpdatedBy(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetUpdatedBy(*s)
	}
	return suo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (suo *SubscriptionUpdateOne) ClearUpdatedBy() *SubscriptionUpdateOne {
	suo.mutation.ClearUpdatedBy()
	return suo
}

// SetLookupKey sets the "lookup_key" field.
func (suo *SubscriptionUpdateOne) SetLookupKey(s string) *SubscriptionUpdateOne {
	suo.mutation.SetLookupKey(s)
	return suo
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableLookupKey(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetLookupKey(*s)
	}
	return suo
}

// ClearLookupKey clears the value of the "lookup_key" field.
func (suo *SubscriptionUpdateOne) ClearLookupKey() *SubscriptionUpdateOne {
	suo.mutation.ClearLookupKey()
	return suo
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (suo *SubscriptionUpdateOne) SetSubscriptionStatus(ts types.SubscriptionStatus) *SubscriptionUpdateOne {
	suo.mutation.SetSubscriptionStatus(ts)
	return suo
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableSubscriptionStatus(ts *types.SubscriptionStatus) *SubscriptionUpdateOne {
	if ts != nil {
		suo.SetSubscriptionStatus(*ts)
	}
	return suo
}

// SetBillingAnchor sets the "billing_anchor" field.
func (suo *SubscriptionUpdateOne) SetBillingAnchor(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetBillingAnchor(t)
	return suo
}

// SetNillableBillingAnchor sets the "billing_anchor" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableBillingAnchor(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetBillingAnchor(*t)
	}
	return suo
}

// SetStartDate sets the "start_date" field.
func (suo *SubscriptionUpdateOne) SetStartDate(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetStartDate(t)
	return suo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableStartDate(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetStartDate(*t)
	}
	return suo
}

// SetEndDate sets the "end_date" field.
func (suo *SubscriptionUpdateOne) SetEndDate(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetEndDate(t)
	return suo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableEndDate(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetEndDate(*t)
	}
	return suo
}

// ClearEndDate clears the value of the "end_date" field.
func (suo *SubscriptionUpdateOne) ClearEndDate() *SubscriptionUpdateOne {
	suo.mutation.ClearEndDate()
	return suo
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (suo *SubscriptionUpdateOne) SetCurrentPeriodStart(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetCurrentPeriodStart(t)
	return suo
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCurrentPeriodStart(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetCurrentPeriodStart(*t)
	}
	return suo
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (suo *SubscriptionUpdateOne) SetCurrentPeriodEnd(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetCurrentPeriodEnd(t)
	return suo
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCurrentPeriodEnd(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetCurrentPeriodEnd(*t)
	}
	return suo
}

// SetCancelledAt sets the "cancelled_at" field.
func (suo *SubscriptionUpdateOne) SetCancelledAt(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetCancelledAt(t)
	return suo
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCancelledAt(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetCancelledAt(*t)
	}
	return suo
}

// ClearCancelledAt clears the value of the "cancelled_at" field.
func (suo *SubscriptionUpdateOne) ClearCancelledAt() *SubscriptionUpdateOne {
	suo.mutation.ClearCancelledAt()
	return suo
}

// SetCancelAt sets the "cancel_at" field.
func (suo *SubscriptionUpdateOne) SetCancelAt(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetCancelAt(t)
	return suo
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCancelAt(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetCancelAt(*t)
	}
	return suo
}

// ClearCancelAt clears the value of the "cancel_at" field.
func (suo *SubscriptionUpdateOne) ClearCancelAt() *SubscriptionUpdateOne {
	suo.mutation.ClearCancelAt()
	return suo
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (suo *SubscriptionUpdateOne) SetCancelAtPeriodEnd(b bool) *SubscriptionUpdateOne {
	suo.mutation.SetCancelAtPeriodEnd(b)
	return suo
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCancelAtPeriodEnd(b *bool) *SubscriptionUpdateOne {
	if b != nil {
		suo.SetCancelAtPeriodEnd(*b)
	}
	return suo
}

// SetTrialStart sets the "trial_start" field.
func (suo *SubscriptionUpdateOne) SetTrialStart(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetTrialStart(t)
	return suo
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableTrialStart(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetTrialStart(*t)
	}
	return suo
}

// ClearTrialStart clears the value of the "trial_start" field.
func (suo *SubscriptionUpdateOne) ClearTrialStart() *SubscriptionUpdateOne {
	suo.mutation.ClearTrialStart()
	return suo
}

// SetTrialEnd sets the "trial_end" field.
func (suo *SubscriptionUpdateOne) SetTrialEnd(t time.Time) *SubscriptionUpdateOne {
	suo.mutation.SetTrialEnd(t)
	return suo
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableTrialEnd(t *time.Time) *SubscriptionUpdateOne {
	if t != nil {
		suo.SetTrialEnd(*t)
	}
	return suo
}

// ClearTrialEnd clears the value of the "trial_end" field.
func (suo *SubscriptionUpdateOne) ClearTrialEnd() *SubscriptionUpdateOne {
	suo.mutation.ClearTrialEnd()
	return suo
}

// SetVersion sets the "version" field.
func (suo *SubscriptionUpdateOne) SetVersion(i int) *SubscriptionUpdateOne {
	suo.mutation.ResetVersion()
	suo.mutation.SetVersion(i)
	return suo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableVersion(i *int) *SubscriptionUpdateOne {
	if i != nil {
		suo.SetVersion(*i)
	}
	return suo
}

// AddVersion adds i to the "version" field.
func (suo *SubscriptionUpdateOne) AddVersion(i int) *SubscriptionUpdateOne {
	suo.mutation.AddVersion(i)
	return suo
}

// SetMetadata sets the "metadata" field.
func (suo *SubscriptionUpdateOne) SetMetadata(m map[string]string) *SubscriptionUpdateOne {
	suo.mutation.SetMetadata(m)
	return suo
}

// ClearMetadata clears the value of the "metadata" field.
func (suo *SubscriptionUpdateOne) ClearMetadata() *SubscriptionUpdateOne {
	suo.mutation.ClearMetadata()
	return suo
}

// SetPauseStatus sets the "pause_status" field.
func (suo *SubscriptionUpdateOne) SetPauseStatus(ts types.PauseStatus) *SubscriptionUpdateOne {
	suo.mutation.SetPauseStatus(ts)
	return suo
}

// SetNillablePauseStatus sets the "pause_status" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillablePauseStatus(ts *types.PauseStatus) *SubscriptionUpdateOne {
	if ts != nil {
		suo.SetPauseStatus(*ts)
	}
	return suo
}

// SetActivePauseID sets the "active_pause_id" field.
func (suo *SubscriptionUpdateOne) SetActivePauseID(s string) *SubscriptionUpdateOne {
	suo.mutation.SetActivePauseID(s)
	return suo
}

// SetNillableActivePauseID sets the "active_pause_id" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableActivePauseID(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetActivePauseID(*s)
	}
	return suo
}

// ClearActivePauseID clears the value of the "active_pause_id" field.
func (suo *SubscriptionUpdateOne) ClearActivePauseID() *SubscriptionUpdateOne {
	suo.mutation.ClearActivePauseID()
	return suo
}

// SetCommitmentAmount sets the "commitment_amount" field.
func (suo *SubscriptionUpdateOne) SetCommitmentAmount(d decimal.Decimal) *SubscriptionUpdateOne {
	suo.mutation.SetCommitmentAmount(d)
	return suo
}

// SetNillableCommitmentAmount sets the "commitment_amount" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCommitmentAmount(d *decimal.Decimal) *SubscriptionUpdateOne {
	if d != nil {
		suo.SetCommitmentAmount(*d)
	}
	return suo
}

// ClearCommitmentAmount clears the value of the "commitment_amount" field.
func (suo *SubscriptionUpdateOne) ClearCommitmentAmount() *SubscriptionUpdateOne {
	suo.mutation.ClearCommitmentAmount()
	return suo
}

// SetOverageFactor sets the "overage_factor" field.
func (suo *SubscriptionUpdateOne) SetOverageFactor(d decimal.Decimal) *SubscriptionUpdateOne {
	suo.mutation.SetOverageFactor(d)
	return suo
}

// SetNillableOverageFactor sets the "overage_factor" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableOverageFactor(d *decimal.Decimal) *SubscriptionUpdateOne {
	if d != nil {
		suo.SetOverageFactor(*d)
	}
	return suo
}

// ClearOverageFactor clears the value of the "overage_factor" field.
func (suo *SubscriptionUpdateOne) ClearOverageFactor() *SubscriptionUpdateOne {
	suo.mutation.ClearOverageFactor()
	return suo
}

// SetPaymentBehavior sets the "payment_behavior" field.
func (suo *SubscriptionUpdateOne) SetPaymentBehavior(tb types.PaymentBehavior) *SubscriptionUpdateOne {
	suo.mutation.SetPaymentBehavior(tb)
	return suo
}

// SetNillablePaymentBehavior sets the "payment_behavior" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillablePaymentBehavior(tb *types.PaymentBehavior) *SubscriptionUpdateOne {
	if tb != nil {
		suo.SetPaymentBehavior(*tb)
	}
	return suo
}

// SetCollectionMethod sets the "collection_method" field.
func (suo *SubscriptionUpdateOne) SetCollectionMethod(tm types.CollectionMethod) *SubscriptionUpdateOne {
	suo.mutation.SetCollectionMethod(tm)
	return suo
}

// SetNillableCollectionMethod sets the "collection_method" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCollectionMethod(tm *types.CollectionMethod) *SubscriptionUpdateOne {
	if tm != nil {
		suo.SetCollectionMethod(*tm)
	}
	return suo
}

// SetGatewayPaymentMethodID sets the "gateway_payment_method_id" field.
func (suo *SubscriptionUpdateOne) SetGatewayPaymentMethodID(s string) *SubscriptionUpdateOne {
	suo.mutation.SetGatewayPaymentMethodID(s)
	return suo
}

// SetNillableGatewayPaymentMethodID sets the "gateway_payment_method_id" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableGatewayPaymentMethodID(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetGatewayPaymentMethodID(*s)
	}
	return suo
}

// ClearGatewayPaymentMethodID clears the value of the "gateway_payment_method_id" field.
func (suo *SubscriptionUpdateOne) ClearGatewayPaymentMethodID() *SubscriptionUpdateOne {
	suo.mutation.ClearGatewayPaymentMethodID()
	return suo
}

// SetInvoiceCadence sets the "invoice_cadence" field.
func (suo *SubscriptionUpdateOne) SetInvoiceCadence(tc types.InvoiceCadence) *SubscriptionUpdateOne {
	suo.mutation.SetInvoiceCadence(tc)
	return suo
}

// SetNillableInvoiceCadence sets the "invoice_cadence" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableInvoiceCadence(tc *types.InvoiceCadence) *SubscriptionUpdateOne {
	if tc != nil {
		suo.SetInvoiceCadence(*tc)
	}
	return suo
}

// SetCustomerTimezone sets the "customer_timezone" field.
func (suo *SubscriptionUpdateOne) SetCustomerTimezone(s string) *SubscriptionUpdateOne {
	suo.mutation.SetCustomerTimezone(s)
	return suo
}

// SetNillableCustomerTimezone sets the "customer_timezone" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableCustomerTimezone(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetCustomerTimezone(*s)
	}
	return suo
}

// SetEnableTrueUp sets the "enable_true_up" field.
func (suo *SubscriptionUpdateOne) SetEnableTrueUp(b bool) *SubscriptionUpdateOne {
	suo.mutation.SetEnableTrueUp(b)
	return suo
}

// SetNillableEnableTrueUp sets the "enable_true_up" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableEnableTrueUp(b *bool) *SubscriptionUpdateOne {
	if b != nil {
		suo.SetEnableTrueUp(*b)
	}
	return suo
}

// SetInvoicingCustomerID sets the "invoicing_customer_id" field.
func (suo *SubscriptionUpdateOne) SetInvoicingCustomerID(s string) *SubscriptionUpdateOne {
	suo.mutation.SetInvoicingCustomerID(s)
	return suo
}

// SetNillableInvoicingCustomerID sets the "invoicing_customer_id" field if the given value is not nil.
func (suo *SubscriptionUpdateOne) SetNillableInvoicingCustomerID(s *string) *SubscriptionUpdateOne {
	if s != nil {
		suo.SetInvoicingCustomerID(*s)
	}
	return suo
}

// ClearInvoicingCustomerID clears the value of the "invoicing_customer_id" field.
func (suo *SubscriptionUpdateOne) ClearInvoicingCustomerID() *SubscriptionUpdateOne {
	suo.mutation.ClearInvoicingCustomerID()
	return suo
}

// AddLineItemIDs adds the "line_items" edge to the SubscriptionLineItem entity by IDs.
func (suo *SubscriptionUpdateOne) AddLineItemIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddLineItemIDs(ids...)
	return suo
}

// AddLineItems adds the "line_items" edges to the SubscriptionLineItem entity.
func (suo *SubscriptionUpdateOne) AddLineItems(s ...*SubscriptionLineItem) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddLineItemIDs(ids...)
}

// AddPauseIDs adds the "pauses" edge to the SubscriptionPause entity by IDs.
func (suo *SubscriptionUpdateOne) AddPauseIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddPauseIDs(ids...)
	return suo
}

// AddPauses adds the "pauses" edges to the SubscriptionPause entity.
func (suo *SubscriptionUpdateOne) AddPauses(s ...*SubscriptionPause) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddPauseIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the SubscriptionPhase entity by IDs.
func (suo *SubscriptionUpdateOne) AddPhaseIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddPhaseIDs(ids...)
	return suo
}

// AddPhases adds the "phases" edges to the SubscriptionPhase entity.
func (suo *SubscriptionUpdateOne) AddPhases(s ...*SubscriptionPhase) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddPhaseIDs(ids...)
}

// AddCreditGrantIDs adds the "credit_grants" edge to the CreditGrant entity by IDs.
func (suo *SubscriptionUpdateOne) AddCreditGrantIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddCreditGrantIDs(ids...)
	return suo
}

// AddCreditGrants adds the "credit_grants" edges to the CreditGrant entity.
func (suo *SubscriptionUpdateOne) AddCreditGrants(c ...*CreditGrant) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.AddCreditGrantIDs(ids...)
}

// AddCouponAssociationIDs adds the "coupon_associations" edge to the CouponAssociation entity by IDs.
func (suo *SubscriptionUpdateOne) AddCouponAssociationIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddCouponAssociationIDs(ids...)
	return suo
}

// AddCouponAssociations adds the "coupon_associations" edges to the CouponAssociation entity.
func (suo *SubscriptionUpdateOne) AddCouponAssociations(c ...*CouponAssociation) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.AddCouponAssociationIDs(ids...)
}

// AddCouponApplicationIDs adds the "coupon_applications" edge to the CouponApplication entity by IDs.
func (suo *SubscriptionUpdateOne) AddCouponApplicationIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.AddCouponApplicationIDs(ids...)
	return suo
}

// AddCouponApplications adds the "coupon_applications" edges to the CouponApplication entity.
func (suo *SubscriptionUpdateOne) AddCouponApplications(c ...*CouponApplication) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.AddCouponApplicationIDs(ids...)
}

// SetInvoicingCustomer sets the "invoicing_customer" edge to the Customer entity.
func (suo *SubscriptionUpdateOne) SetInvoicingCustomer(c *Customer) *SubscriptionUpdateOne {
	return suo.SetInvoicingCustomerID(c.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (suo *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return suo.mutation
}

// ClearLineItems clears all "line_items" edges to the SubscriptionLineItem entity.
func (suo *SubscriptionUpdateOne) ClearLineItems() *SubscriptionUpdateOne {
	suo.mutation.ClearLineItems()
	return suo
}

// RemoveLineItemIDs removes the "line_items" edge to SubscriptionLineItem entities by IDs.
func (suo *SubscriptionUpdateOne) RemoveLineItemIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemoveLineItemIDs(ids...)
	return suo
}

// RemoveLineItems removes "line_items" edges to SubscriptionLineItem entities.
func (suo *SubscriptionUpdateOne) RemoveLineItems(s ...*SubscriptionLineItem) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveLineItemIDs(ids...)
}

// ClearPauses clears all "pauses" edges to the SubscriptionPause entity.
func (suo *SubscriptionUpdateOne) ClearPauses() *SubscriptionUpdateOne {
	suo.mutation.ClearPauses()
	return suo
}

// RemovePauseIDs removes the "pauses" edge to SubscriptionPause entities by IDs.
func (suo *SubscriptionUpdateOne) RemovePauseIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemovePauseIDs(ids...)
	return suo
}

// RemovePauses removes "pauses" edges to SubscriptionPause entities.
func (suo *SubscriptionUpdateOne) RemovePauses(s ...*SubscriptionPause) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemovePauseIDs(ids...)
}

// ClearPhases clears all "phases" edges to the SubscriptionPhase entity.
func (suo *SubscriptionUpdateOne) ClearPhases() *SubscriptionUpdateOne {
	suo.mutation.ClearPhases()
	return suo
}

// RemovePhaseIDs removes the "phases" edge to SubscriptionPhase entities by IDs.
func (suo *SubscriptionUpdateOne) RemovePhaseIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemovePhaseIDs(ids...)
	return suo
}

// RemovePhases removes "phases" edges to SubscriptionPhase entities.
func (suo *SubscriptionUpdateOne) RemovePhases(s ...*SubscriptionPhase) *SubscriptionUpdateOne {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemovePhaseIDs(ids...)
}

// ClearCreditGrants clears all "credit_grants" edges to the CreditGrant entity.
func (suo *SubscriptionUpdateOne) ClearCreditGrants() *SubscriptionUpdateOne {
	suo.mutation.ClearCreditGrants()
	return suo
}

// RemoveCreditGrantIDs removes the "credit_grants" edge to CreditGrant entities by IDs.
func (suo *SubscriptionUpdateOne) RemoveCreditGrantIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemoveCreditGrantIDs(ids...)
	return suo
}

// RemoveCreditGrants removes "credit_grants" edges to CreditGrant entities.
func (suo *SubscriptionUpdateOne) RemoveCreditGrants(c ...*CreditGrant) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.RemoveCreditGrantIDs(ids...)
}

// ClearCouponAssociations clears all "coupon_associations" edges to the CouponAssociation entity.
func (suo *SubscriptionUpdateOne) ClearCouponAssociations() *SubscriptionUpdateOne {
	suo.mutation.ClearCouponAssociations()
	return suo
}

// RemoveCouponAssociationIDs removes the "coupon_associations" edge to CouponAssociation entities by IDs.
func (suo *SubscriptionUpdateOne) RemoveCouponAssociationIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemoveCouponAssociationIDs(ids...)
	return suo
}

// RemoveCouponAssociations removes "coupon_associations" edges to CouponAssociation entities.
func (suo *SubscriptionUpdateOne) RemoveCouponAssociations(c ...*CouponAssociation) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.RemoveCouponAssociationIDs(ids...)
}

// ClearCouponApplications clears all "coupon_applications" edges to the CouponApplication entity.
func (suo *SubscriptionUpdateOne) ClearCouponApplications() *SubscriptionUpdateOne {
	suo.mutation.ClearCouponApplications()
	return suo
}

// RemoveCouponApplicationIDs removes the "coupon_applications" edge to CouponApplication entities by IDs.
func (suo *SubscriptionUpdateOne) RemoveCouponApplicationIDs(ids ...string) *SubscriptionUpdateOne {
	suo.mutation.RemoveCouponApplicationIDs(ids...)
	return suo
}

// RemoveCouponApplications removes "coupon_applications" edges to CouponApplication entities.
func (suo *SubscriptionUpdateOne) RemoveCouponApplications(c ...*CouponApplication) *SubscriptionUpdateOne {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return suo.RemoveCouponApplicationIDs(ids...)
}

// ClearInvoicingCustomer clears the "invoicing_customer" edge to the Customer entity.
func (suo *SubscriptionUpdateOne) ClearInvoicingCustomer() *SubscriptionUpdateOne {
	suo.mutation.ClearInvoicingCustomer()
	return suo
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (suo *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Subscription entity.
func (suo *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	suo.defaults()
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *SubscriptionUpdateOne) defaults() {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		v := subscription.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
}

func (suo *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
	}
	if suo.mutation.CreatedByCleared() {
		_spec.ClearField(subscription.FieldCreatedBy, field.TypeString)
	}
	if value, ok := suo.mutation.UpdatedBy(); ok {
		_spec.SetField(subscription.FieldUpdatedBy, field.TypeString, value)
	}
	if suo.mutation.UpdatedByCleared() {
		_spec.ClearField(subscription.FieldUpdatedBy, field.TypeString)
	}
	if suo.mutation.EnvironmentIDCleared() {
		_spec.ClearField(subscription.FieldEnvironmentID, field.TypeString)
	}
	if value, ok := suo.mutation.LookupKey(); ok {
		_spec.SetField(subscription.FieldLookupKey, field.TypeString, value)
	}
	if suo.mutation.LookupKeyCleared() {
		_spec.ClearField(subscription.FieldLookupKey, field.TypeString)
	}
	if value, ok := suo.mutation.SubscriptionStatus(); ok {
		_spec.SetField(subscription.FieldSubscriptionStatus, field.TypeString, value)
	}
	if value, ok := suo.mutation.BillingAnchor(); ok {
		_spec.SetField(subscription.FieldBillingAnchor, field.TypeTime, value)
	}
	if value, ok := suo.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := suo.mutation.EndDate(); ok {
		_spec.SetField(subscription.FieldEndDate, field.TypeTime, value)
	}
	if suo.mutation.EndDateCleared() {
		_spec.ClearField(subscription.FieldEndDate, field.TypeTime)
	}
	if value, ok := suo.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
	}
	if value, ok := suo.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
	}
	if value, ok := suo.mutation.CancelledAt(); ok {
		_spec.SetField(subscription.FieldCancelledAt, field.TypeTime, value)
	}
	if suo.mutation.CancelledAtCleared() {
		_spec.ClearField(subscription.FieldCancelledAt, field.TypeTime)
	}
	if value, ok := suo.mutation.CancelAt(); ok {
		_spec.SetField(subscription.FieldCancelAt, field.TypeTime, value)
	}
	if suo.mutation.CancelAtCleared() {
		_spec.ClearField(subscription.FieldCancelAt, field.TypeTime)
	}
	if value, ok := suo.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
	}
	if value, ok := suo.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
	}
	if suo.mutation.TrialStartCleared() {
		_spec.ClearField(subscription.FieldTrialStart, field.TypeTime)
	}
	if value, ok := suo.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
	}
	if suo.mutation.TrialEndCleared() {
		_spec.ClearField(subscription.FieldTrialEnd, field.TypeTime)
	}
	if value, ok := suo.mutation.Version(); ok {
		_spec.SetField(subscription.FieldVersion, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedVersion(); ok {
		_spec.AddField(subscription.FieldVersion, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
	}
	if suo.mutation.MetadataCleared() {
		_spec.ClearField(subscription.FieldMetadata, field.TypeJSON)
	}
	if value, ok := suo.mutation.PauseStatus(); ok {
		_spec.SetField(subscription.FieldPauseStatus, field.TypeString, value)
	}
	if value, ok := suo.mutation.ActivePauseID(); ok {
		_spec.SetField(subscription.FieldActivePauseID, field.TypeString, value)
	}
	if suo.mutation.ActivePauseIDCleared() {
		_spec.ClearField(subscription.FieldActivePauseID, field.TypeString)
	}
	if value, ok := suo.mutation.CommitmentAmount(); ok {
		_spec.SetField(subscription.FieldCommitmentAmount, field.TypeOther, value)
	}
	if suo.mutation.CommitmentAmountCleared() {
		_spec.ClearField(subscription.FieldCommitmentAmount, field.TypeOther)
	}
	if value, ok := suo.mutation.OverageFactor(); ok {
		_spec.SetField(subscription.FieldOverageFactor, field.TypeOther, value)
	}
	if suo.mutation.OverageFactorCleared() {
		_spec.ClearField(subscription.FieldOverageFactor, field.TypeOther)
	}
	if value, ok := suo.mutation.PaymentBehavior(); ok {
		_spec.SetField(subscription.FieldPaymentBehavior, field.TypeString, value)
	}
	if value, ok := suo.mutation.CollectionMethod(); ok {
		_spec.SetField(subscription.FieldCollectionMethod, field.TypeString, value)
	}
	if value, ok := suo.mutation.GatewayPaymentMethodID(); ok {
		_spec.SetField(subscription.FieldGatewayPaymentMethodID, field.TypeString, value)
	}
	if suo.mutation.GatewayPaymentMethodIDCleared() {
		_spec.ClearField(subscription.FieldGatewayPaymentMethodID, field.TypeString)
	}
	if value, ok := suo.mutation.InvoiceCadence(); ok {
		_spec.SetField(subscription.FieldInvoiceCadence, field.TypeString, value)
	}
	if value, ok := suo.mutation.CustomerTimezone(); ok {
		_spec.SetField(subscription.FieldCustomerTimezone, field.TypeString, value)
	}
	if value, ok := suo.mutation.EnableTrueUp(); ok {
		_spec.SetField(subscription.FieldEnableTrueUp, field.TypeBool, value)
	}
	if suo.mutation.LineItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedLineItemsIDs(); len(nodes) > 0 && !suo.mutation.LineItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.LineItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PausesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPausesIDs(); len(nodes) > 0 && !suo.mutation.PausesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PausesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPhasesIDs(); len(nodes) > 0 && !suo.mutation.PhasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.CreditGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedCreditGrantsIDs(); len(nodes) > 0 && !suo.mutation.CreditGrantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.CreditGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.CouponAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedCouponAssociationsIDs(); len(nodes) > 0 && !suo.mutation.CouponAssociationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.CouponAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.CouponApplicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedCouponApplicationsIDs(); len(nodes) > 0 && !suo.mutation.CouponApplicationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.CouponApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.InvoicingCustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.InvoicingCustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
