// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/flexprice/flexprice/ent/couponapplication"
	"github.com/flexprice/flexprice/ent/couponassociation"
	"github.com/flexprice/flexprice/ent/creditgrant"
	"github.com/flexprice/flexprice/ent/customer"
	"github.com/flexprice/flexprice/ent/subscription"
	"github.com/flexprice/flexprice/ent/subscriptionlineitem"
	"github.com/flexprice/flexprice/ent/subscriptionpause"
	"github.com/flexprice/flexprice/ent/subscriptionphase"
	"github.com/flexprice/flexprice/internal/types"
	"github.com/shopspring/decimal"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (sc *SubscriptionCreate) SetTenantID(s string) *SubscriptionCreate {
	sc.mutation.SetTenantID(s)
	return sc
}

// SetStatus sets the "status" field.
func (sc *SubscriptionCreate) SetStatus(s string) *SubscriptionCreate {
	sc.mutation.SetStatus(s)
	return sc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableStatus(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetStatus(*s)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *SubscriptionCreate) SetCreatedAt(t time.Time) *SubscriptionCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCreatedAt(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *SubscriptionCreate) SetUpdatedAt(t time.Time) *SubscriptionCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableUpdatedAt(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetCreatedBy sets the "created_by" field.
func (sc *SubscriptionCreate) SetCreatedBy(s string) *SubscriptionCreate {
	sc.mutation.SetCreatedBy(s)
	return sc
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCreatedBy(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetCreatedBy(*s)
	}
	return sc
}

// SetUpdatedBy sets the "updated_by" field.
func (sc *SubscriptionCreate) SetUpdatedBy(s string) *SubscriptionCreate {
	sc.mutation.SetUpdatedBy(s)
	return sc
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableUpdatedBy(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetUpdatedBy(*s)
	}
	return sc
}

// SetEnvironmentID sets the "environment_id" field.
func (sc *SubscriptionCreate) SetEnvironmentID(s string) *SubscriptionCreate {
	sc.mutation.SetEnvironmentID(s)
	return sc
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableEnvironmentID(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetEnvironmentID(*s)
	}
	return sc
}

// SetLookupKey sets the "lookup_key" field.
func (sc *SubscriptionCreate) SetLookupKey(s string) *SubscriptionCreate {
	sc.mutation.SetLookupKey(s)
	return sc
}

// SetNillableLookupKey sets the "lookup_key" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableLookupKey(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetLookupKey(*s)
	}
	return sc
}

// SetCustomerID sets the "customer_id" field.
func (sc *SubscriptionCreate) SetCustomerID(s string) *SubscriptionCreate {
	sc.mutation.SetCustomerID(s)
	return sc
}

// SetPlanID sets the "plan_id" field.
func (sc *SubscriptionCreate) SetPlanID(s string) *SubscriptionCreate {
	sc.mutation.SetPlanID(s)
	return sc
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (sc *SubscriptionCreate) SetSubscriptionStatus(ts types.SubscriptionStatus) *SubscriptionCreate {
	sc.mutation.SetSubscriptionStatus(ts)
	return sc
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableSubscriptionStatus(ts *types.SubscriptionStatus) *SubscriptionCreate {
	if ts != nil {
		sc.SetSubscriptionStatus(*ts)
	}
	return sc
}

// SetCurrency sets the "currency" field.
func (sc *SubscriptionCreate) SetCurrency(s string) *SubscriptionCreate {
	sc.mutation.SetCurrency(s)
	return sc
}

// SetBillingAnchor sets the "billing_anchor" field.
func (sc *SubscriptionCreate) SetBillingAnchor(t time.Time) *SubscriptionCreate {
	sc.mutation.SetBillingAnchor(t)
	return sc
}

// SetNillableBillingAnchor sets the "billing_anchor" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableBillingAnchor(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetBillingAnchor(*t)
	}
	return sc
}

// SetStartDate sets the "start_date" field.
func (sc *SubscriptionCreate) SetStartDate(t time.Time) *SubscriptionCreate {
	sc.mutation.SetStartDate(t)
	return sc
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableStartDate(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetStartDate(*t)
	}
	return sc
}

// SetEndDate sets the "end_date" field.
func (sc *SubscriptionCreate) SetEndDate(t time.Time) *SubscriptionCreate {
	sc.mutation.SetEndDate(t)
	return sc
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableEndDate(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetEndDate(*t)
	}
	return sc
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (sc *SubscriptionCreate) SetCurrentPeriodStart(t time.Time) *SubscriptionCreate {
	sc.mutation.SetCurrentPeriodStart(t)
	return sc
}

// SetNillableCurrentPeriodStart sets the "current_period_start" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCurrentPeriodStart(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetCurrentPeriodStart(*t)
	}
	return sc
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (sc *SubscriptionCreate) SetCurrentPeriodEnd(t time.Time) *SubscriptionCreate {
	sc.mutation.SetCurrentPeriodEnd(t)
	return sc
}

// SetNillableCurrentPeriodEnd sets the "current_period_end" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCurrentPeriodEnd(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetCurrentPeriodEnd(*t)
	}
	return sc
}

// SetCancelledAt sets the "cancelled_at" field.
func (sc *SubscriptionCreate) SetCancelledAt(t time.Time) *SubscriptionCreate {
	sc.mutation.SetCancelledAt(t)
	return sc
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCancelledAt(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetCancelledAt(*t)
	}
	return sc
}

// SetCancelAt sets the "cancel_at" field.
func (sc *SubscriptionCreate) SetCancelAt(t time.Time) *SubscriptionCreate {
	sc.mutation.SetCancelAt(t)
	return sc
}

// SetNillableCancelAt sets the "cancel_at" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCancelAt(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetCancelAt(*t)
	}
	return sc
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (sc *SubscriptionCreate) SetCancelAtPeriodEnd(b bool) *SubscriptionCreate {
	sc.mutation.SetCancelAtPeriodEnd(b)
	return sc
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCancelAtPeriodEnd(b *bool) *SubscriptionCreate {
	if b != nil {
		sc.SetCancelAtPeriodEnd(*b)
	}
	return sc
}

// SetTrialStart sets the "trial_start" field.
func (sc *SubscriptionCreate) SetTrialStart(t time.Time) *SubscriptionCreate {
	sc.mutation.SetTrialStart(t)
	return sc
}

// SetNillableTrialStart sets the "trial_start" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableTrialStart(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetTrialStart(*t)
	}
	return sc
}

// SetTrialEnd sets the "trial_end" field.
func (sc *SubscriptionCreate) SetTrialEnd(t time.Time) *SubscriptionCreate {
	sc.mutation.SetTrialEnd(t)
	return sc
}

// SetNillableTrialEnd sets the "trial_end" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableTrialEnd(t *time.Time) *SubscriptionCreate {
	if t != nil {
		sc.SetTrialEnd(*t)
	}
	return sc
}

// SetBillingCadence sets the "billing_cadence" field.
func (sc *SubscriptionCreate) SetBillingCadence(tc types.BillingCadence) *SubscriptionCreate {
	sc.mutation.SetBillingCadence(tc)
	return sc
}

// SetBillingPeriod sets the "billing_period" field.
func (sc *SubscriptionCreate) SetBillingPeriod(tp types.BillingPeriod) *SubscriptionCreate {
	sc.mutation.SetBillingPeriod(tp)
	return sc
}

// SetBillingPeriodCount sets the "billing_period_count" field.
func (sc *SubscriptionCreate) SetBillingPeriodCount(i int) *SubscriptionCreate {
	sc.mutation.SetBillingPeriodCount(i)
	return sc
}

// SetNillableBillingPeriodCount sets the "billing_period_count" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableBillingPeriodCount(i *int) *SubscriptionCreate {
	if i != nil {
		sc.SetBillingPeriodCount(*i)
	}
	return sc
}

// SetVersion sets the "version" field.
func (sc *SubscriptionCreate) SetVersion(i int) *SubscriptionCreate {
	sc.mutation.SetVersion(i)
	return sc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableVersion(i *int) *SubscriptionCreate {
	if i != nil {
		sc.SetVersion(*i)
	}
	return sc
}

// SetMetadata sets the "metadata" field.
func (sc *SubscriptionCreate) SetMetadata(m map[string]string) *SubscriptionCreate {
	sc.mutation.SetMetadata(m)
	return sc
}

// SetPauseStatus sets the "pause_status" field.
func (sc *SubscriptionCreate) SetPauseStatus(ts types.PauseStatus) *SubscriptionCreate {
	sc.mutation.SetPauseStatus(ts)
	return sc
}

// SetNillablePauseStatus sets the "pause_status" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillablePauseStatus(ts *types.PauseStatus) *SubscriptionCreate {
	if ts != nil {
		sc.SetPauseStatus(*ts)
	}
	return sc
}

// SetActivePauseID sets the "active_pause_id" field.
func (sc *SubscriptionCreate) SetActivePauseID(s string) *SubscriptionCreate {
	sc.mutation.SetActivePauseID(s)
	return sc
}

// SetNillableActivePauseID sets the "active_pause_id" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableActivePauseID(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetActivePauseID(*s)
	}
	return sc
}

// SetBillingCycle sets the "billing_cycle" field.
func (sc *SubscriptionCreate) SetBillingCycle(tc types.BillingCycle) *SubscriptionCreate {
	sc.mutation.SetBillingCycle(tc)
	return sc
}

// SetNillableBillingCycle sets the "billing_cycle" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableBillingCycle(tc *types.BillingCycle) *SubscriptionCreate {
	if tc != nil {
		sc.SetBillingCycle(*tc)
	}
	return sc
}

// SetCommitmentAmount sets the "commitment_amount" field.
func (sc *SubscriptionCreate) SetCommitmentAmount(d decimal.Decimal) *SubscriptionCreate {
	sc.mutation.SetCommitmentAmount(d)
	return sc
}

// SetNillableCommitmentAmount sets the "commitment_amount" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCommitmentAmount(d *decimal.Decimal) *SubscriptionCreate {
	if d != nil {
		sc.SetCommitmentAmount(*d)
	}
	return sc
}

// SetOverageFactor sets the "overage_factor" field.
func (sc *SubscriptionCreate) SetOverageFactor(d decimal.Decimal) *SubscriptionCreate {
	sc.mutation.SetOverageFactor(d)
	return sc
}

// SetNillableOverageFactor sets the "overage_factor" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableOverageFactor(d *decimal.Decimal) *SubscriptionCreate {
	if d != nil {
		sc.SetOverageFactor(*d)
	}
	return sc
}

// SetPaymentBehavior sets the "payment_behavior" field.
func (sc *SubscriptionCreate) SetPaymentBehavior(tb types.PaymentBehavior) *SubscriptionCreate {
	sc.mutation.SetPaymentBehavior(tb)
	return sc
}

// SetNillablePaymentBehavior sets the "payment_behavior" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillablePaymentBehavior(tb *types.PaymentBehavior) *SubscriptionCreate {
	if tb != nil {
		sc.SetPaymentBehavior(*tb)
	}
	return sc
}

// SetCollectionMethod sets the "collection_method" field.
func (sc *SubscriptionCreate) SetCollectionMethod(tm types.CollectionMethod) *SubscriptionCreate {
	sc.mutation.SetCollectionMethod(tm)
	return sc
}

// SetNillableCollectionMethod sets the "collection_method" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCollectionMethod(tm *types.CollectionMethod) *SubscriptionCreate {
	if tm != nil {
		sc.SetCollectionMethod(*tm)
	}
	return sc
}

// SetGatewayPaymentMethodID sets the "gateway_payment_method_id" field.
func (sc *SubscriptionCreate) SetGatewayPaymentMethodID(s string) *SubscriptionCreate {
	sc.mutation.SetGatewayPaymentMethodID(s)
	return sc
}

// SetNillableGatewayPaymentMethodID sets the "gateway_payment_method_id" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableGatewayPaymentMethodID(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetGatewayPaymentMethodID(*s)
	}
	return sc
}

// SetInvoiceCadence sets the "invoice_cadence" field.
func (sc *SubscriptionCreate) SetInvoiceCadence(tc types.InvoiceCadence) *SubscriptionCreate {
	sc.mutation.SetInvoiceCadence(tc)
	return sc
}

// SetNillableInvoiceCadence sets the "invoice_cadence" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableInvoiceCadence(tc *types.InvoiceCadence) *SubscriptionCreate {
	if tc != nil {
		sc.SetInvoiceCadence(*tc)
	}
	return sc
}

// SetCustomerTimezone sets the "customer_timezone" field.
func (sc *SubscriptionCreate) SetCustomerTimezone(s string) *SubscriptionCreate {
	sc.mutation.SetCustomerTimezone(s)
	return sc
}

// SetNillableCustomerTimezone sets the "customer_timezone" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableCustomerTimezone(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetCustomerTimezone(*s)
	}
	return sc
}

// SetProrationBehavior sets the "proration_behavior" field.
func (sc *SubscriptionCreate) SetProrationBehavior(tb types.ProrationBehavior) *SubscriptionCreate {
	sc.mutation.SetProrationBehavior(tb)
	return sc
}

// SetNillableProrationBehavior sets the "proration_behavior" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableProrationBehavior(tb *types.ProrationBehavior) *SubscriptionCreate {
	if tb != nil {
		sc.SetProrationBehavior(*tb)
	}
	return sc
}

// SetEnableTrueUp sets the "enable_true_up" field.
func (sc *SubscriptionCreate) SetEnableTrueUp(b bool) *SubscriptionCreate {
	sc.mutation.SetEnableTrueUp(b)
	return sc
}

// SetNillableEnableTrueUp sets the "enable_true_up" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableEnableTrueUp(b *bool) *SubscriptionCreate {
	if b != nil {
		sc.SetEnableTrueUp(*b)
	}
	return sc
}

// SetInvoicingCustomerID sets the "invoicing_customer_id" field.
func (sc *SubscriptionCreate) SetInvoicingCustomerID(s string) *SubscriptionCreate {
	sc.mutation.SetInvoicingCustomerID(s)
	return sc
}

// SetNillableInvoicingCustomerID sets the "invoicing_customer_id" field if the given value is not nil.
func (sc *SubscriptionCreate) SetNillableInvoicingCustomerID(s *string) *SubscriptionCreate {
	if s != nil {
		sc.SetInvoicingCustomerID(*s)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SubscriptionCreate) SetID(s string) *SubscriptionCreate {
	sc.mutation.SetID(s)
	return sc
}

// AddLineItemIDs adds the "line_items" edge to the SubscriptionLineItem entity by IDs.
func (sc *SubscriptionCreate) AddLineItemIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddLineItemIDs(ids...)
	return sc
}

// AddLineItems adds the "line_items" edges to the SubscriptionLineItem entity.
func (sc *SubscriptionCreate) AddLineItems(s ...*SubscriptionLineItem) *SubscriptionCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddLineItemIDs(ids...)
}

// AddPauseIDs adds the "pauses" edge to the SubscriptionPause entity by IDs.
func (sc *SubscriptionCreate) AddPauseIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddPauseIDs(ids...)
	return sc
}

// AddPauses adds the "pauses" edges to the SubscriptionPause entity.
func (sc *SubscriptionCreate) AddPauses(s ...*SubscriptionPause) *SubscriptionCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddPauseIDs(ids...)
}

// AddPhaseIDs adds the "phases" edge to the SubscriptionPhase entity by IDs.
func (sc *SubscriptionCreate) AddPhaseIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddPhaseIDs(ids...)
	return sc
}

// AddPhases adds the "phases" edges to the SubscriptionPhase entity.
func (sc *SubscriptionCreate) AddPhases(s ...*SubscriptionPhase) *SubscriptionCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddPhaseIDs(ids...)
}

// AddCreditGrantIDs adds the "credit_grants" edge to the CreditGrant entity by IDs.
func (sc *SubscriptionCreate) AddCreditGrantIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddCreditGrantIDs(ids...)
	return sc
}

// AddCreditGrants adds the "credit_grants" edges to the CreditGrant entity.
func (sc *SubscriptionCreate) AddCreditGrants(c ...*CreditGrant) *SubscriptionCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return sc.AddCreditGrantIDs(ids...)
}

// AddCouponAssociationIDs adds the "coupon_associations" edge to the CouponAssociation entity by IDs.
func (sc *SubscriptionCreate) AddCouponAssociationIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddCouponAssociationIDs(ids...)
	return sc
}

// AddCouponAssociations adds the "coupon_associations" edges to the CouponAssociation entity.
func (sc *SubscriptionCreate) AddCouponAssociations(c ...*CouponAssociation) *SubscriptionCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return sc.AddCouponAssociationIDs(ids...)
}

// AddCouponApplicationIDs adds the "coupon_applications" edge to the CouponApplication entity by IDs.
func (sc *SubscriptionCreate) AddCouponApplicationIDs(ids ...string) *SubscriptionCreate {
	sc.mutation.AddCouponApplicationIDs(ids...)
	return sc
}

// AddCouponApplications adds the "coupon_applications" edges to the CouponApplication entity.
func (sc *SubscriptionCreate) AddCouponApplications(c ...*CouponApplication) *SubscriptionCreate {
	ids := make([]string, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return sc.AddCouponApplicationIDs(ids...)
}

// SetInvoicingCustomer sets the "invoicing_customer" edge to the Customer entity.
func (sc *SubscriptionCreate) SetInvoicingCustomer(c *Customer) *SubscriptionCreate {
	return sc.SetInvoicingCustomerID(c.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (sc *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return sc.mutation
}

// Save creates the Subscription in the database.
func (sc *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	sc.defaults()
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SubscriptionCreate) defaults() {
	if _, ok := sc.mutation.Status(); !ok {
		v := subscription.DefaultStatus
		sc.mutation.SetStatus(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		v := subscription.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		v := subscription.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	if _, ok := sc.mutation.EnvironmentID(); !ok {
		v := subscription.DefaultEnvironmentID
		sc.mutation.SetEnvironmentID(v)
	}
	if _, ok := sc.mutation.SubscriptionStatus(); !ok {
		v := subscription.DefaultSubscriptionStatus
		sc.mutation.SetSubscriptionStatus(v)
	}
	if _, ok := sc.mutation.BillingAnchor(); !ok {
		v := subscription.DefaultBillingAnchor()
		sc.mutation.SetBillingAnchor(v)
	}
	if _, ok := sc.mutation.StartDate(); !ok {
		v := subscription.DefaultStartDate()
		sc.mutation.SetStartDate(v)
	}
	if _, ok := sc.mutation.CurrentPeriodStart(); !ok {
		v := subscription.DefaultCurrentPeriodStart()
		sc.mutation.SetCurrentPeriodStart(v)
	}
	if _, ok := sc.mutation.CurrentPeriodEnd(); !ok {
		v := subscription.DefaultCurrentPeriodEnd()
		sc.mutation.SetCurrentPeriodEnd(v)
	}
	if _, ok := sc.mutation.CancelAtPeriodEnd(); !ok {
		v := subscription.DefaultCancelAtPeriodEnd
		sc.mutation.SetCancelAtPeriodEnd(v)
	}
	if _, ok := sc.mutation.BillingPeriodCount(); !ok {
		v := subscription.DefaultBillingPeriodCount
		sc.mutation.SetBillingPeriodCount(v)
	}
	if _, ok := sc.mutation.Version(); !ok {
		v := subscription.DefaultVersion
		sc.mutation.SetVersion(v)
	}
	if _, ok := sc.mutation.PauseStatus(); !ok {
		v := subscription.DefaultPauseStatus
		sc.mutation.SetPauseStatus(v)
	}
	if _, ok := sc.mutation.BillingCycle(); !ok {
		v := subscription.DefaultBillingCycle
		sc.mutation.SetBillingCycle(v)
	}
	if _, ok := sc.mutation.OverageFactor(); !ok {
		v := subscription.DefaultOverageFactor
		sc.mutation.SetOverageFactor(v)
	}
	if _, ok := sc.mutation.PaymentBehavior(); !ok {
		v := subscription.DefaultPaymentBehavior
		sc.mutation.SetPaymentBehavior(v)
	}
	if _, ok := sc.mutation.CollectionMethod(); !ok {
		v := subscription.DefaultCollectionMethod
		sc.mutation.SetCollectionMethod(v)
	}
	if _, ok := sc.mutation.InvoiceCadence(); !ok {
		v := subscription.DefaultInvoiceCadence
		sc.mutation.SetInvoiceCadence(v)
	}
	if _, ok := sc.mutation.CustomerTimezone(); !ok {
		v := subscription.DefaultCustomerTimezone
		sc.mutation.SetCustomerTimezone(v)
	}
	if _, ok := sc.mutation.ProrationBehavior(); !ok {
		v := subscription.DefaultProrationBehavior
		sc.mutation.SetProrationBehavior(v)
	}
	if _, ok := sc.mutation.EnableTrueUp(); !ok {
		v := subscription.DefaultEnableTrueUp
		sc.mutation.SetEnableTrueUp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SubscriptionCreate) check() error {
	if _, ok := sc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Subscription.tenant_id"`)}
	}
	if v, ok := sc.mutation.TenantID(); ok {
		if err := subscription.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.tenant_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Subscription.status"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Subscription.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Subscription.updated_at"`)}
	}
	if _, ok := sc.mutation.CustomerID(); !ok {
		return &ValidationError{Name: "customer_id", err: errors.New(`ent: missing required field "Subscription.customer_id"`)}
	}
	if v, ok := sc.mutation.CustomerID(); ok {
		if err := subscription.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.customer_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "Subscription.plan_id"`)}
	}
	if v, ok := sc.mutation.PlanID(); ok {
		if err := subscription.PlanIDValidator(v); err != nil {
			return &ValidationError{Name: "plan_id", err: fmt.Errorf(`ent: validator failed for field "Subscription.plan_id": %w`, err)}
		}
	}
	if _, ok := sc.mutation.SubscriptionStatus(); !ok {
		return &ValidationError{Name: "subscription_status", err: errors.New(`ent: missing required field "Subscription.subscription_status"`)}
	}
	if v, ok := sc.mutation.SubscriptionStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "subscription_status", err: fmt.Errorf(`ent: validator failed for field "Subscription.subscription_status": %w`, err)}
		}
	}
	if _, ok := sc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Subscription.currency"`)}
	}
	if v, ok := sc.mutation.Currency(); ok {
		if err := subscription.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Subscription.currency": %w`, err)}
		}
	}
	if _, ok := sc.mutation.BillingAnchor(); !ok {
		return &ValidationError{Name: "billing_anchor", err: errors.New(`ent: missing required field "Subscription.billing_anchor"`)}
	}
	if _, ok := sc.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Subscription.start_date"`)}
	}
	if _, ok := sc.mutation.CurrentPeriodStart(); !ok {
		return &ValidationError{Name: "current_period_start", err: errors.New(`ent: missing required field "Subscription.current_period_start"`)}
	}
	if _, ok := sc.mutation.CurrentPeriodEnd(); !ok {
		return &ValidationError{Name: "current_period_end", err: errors.New(`ent: missing required field "Subscription.current_period_end"`)}
	}
	if _, ok := sc.mutation.CancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "cancel_at_period_end", err: errors.New(`ent: missing required field "Subscription.cancel_at_period_end"`)}
	}
	if _, ok := sc.mutation.BillingCadence(); !ok {
		return &ValidationError{Name: "billing_cadence", err: errors.New(`ent: missing required field "Subscription.billing_cadence"`)}
	}
	if v, ok := sc.mutation.BillingCadence(); ok {
		if err := subscription.BillingCadenceValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_cadence", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_cadence": %w`, err)}
		}
	}
	if _, ok := sc.mutation.BillingPeriod(); !ok {
		return &ValidationError{Name: "billing_period", err: errors.New(`ent: missing required field "Subscription.billing_period"`)}
	}
	if v, ok := sc.mutation.BillingPeriod(); ok {
		if err := subscription.BillingPeriodValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_period", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_period": %w`, err)}
		}
	}
	if _, ok := sc.mutation.BillingPeriodCount(); !ok {
		return &ValidationError{Name: "billing_period_count", err: errors.New(`ent: missing required field "Subscription.billing_period_count"`)}
	}
	if _, ok := sc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Subscription.version"`)}
	}
	if _, ok := sc.mutation.PauseStatus(); !ok {
		return &ValidationError{Name: "pause_status", err: errors.New(`ent: missing required field "Subscription.pause_status"`)}
	}
	if v, ok := sc.mutation.PauseStatus(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "pause_status", err: fmt.Errorf(`ent: validator failed for field "Subscription.pause_status": %w`, err)}
		}
	}
	if _, ok := sc.mutation.BillingCycle(); !ok {
		return &ValidationError{Name: "billing_cycle", err: errors.New(`ent: missing required field "Subscription.billing_cycle"`)}
	}
	if v, ok := sc.mutation.BillingCycle(); ok {
		if err := subscription.BillingCycleValidator(string(v)); err != nil {
			return &ValidationError{Name: "billing_cycle", err: fmt.Errorf(`ent: validator failed for field "Subscription.billing_cycle": %w`, err)}
		}
	}
	if _, ok := sc.mutation.PaymentBehavior(); !ok {
		return &ValidationError{Name: "payment_behavior", err: errors.New(`ent: missing required field "Subscription.payment_behavior"`)}
	}
	if v, ok := sc.mutation.PaymentBehavior(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "payment_behavior", err: fmt.Errorf(`ent: validator failed for field "Subscription.payment_behavior": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CollectionMethod(); !ok {
		return &ValidationError{Name: "collection_method", err: errors.New(`ent: missing required field "Subscription.collection_method"`)}
	}
	if v, ok := sc.mutation.CollectionMethod(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "collection_method", err: fmt.Errorf(`ent: validator failed for field "Subscription.collection_method": %w`, err)}
		}
	}
	if _, ok := sc.mutation.InvoiceCadence(); !ok {
		return &ValidationError{Name: "invoice_cadence", err: errors.New(`ent: missing required field "Subscription.invoice_cadence"`)}
	}
	if v, ok := sc.mutation.InvoiceCadence(); ok {
		if err := v.Validate(); err != nil {
			return &ValidationError{Name: "invoice_cadence", err: fmt.Errorf(`ent: validator failed for field "Subscription.invoice_cadence": %w`, err)}
		}
	}
	if _, ok := sc.mutation.CustomerTimezone(); !ok {
		return &ValidationError{Name: "customer_timezone", err: errors.New(`ent: missing required field "Subscription.customer_timezone"`)}
	}
	if _, ok := sc.mutation.ProrationBehavior(); !ok {
		return &ValidationError{Name: "proration_behavior", err: errors.New(`ent: missing required field "Subscription.proration_behavior"`)}
	}
	if v, ok := sc.mutation.ProrationBehavior(); ok {
		if err := subscription.ProrationBehaviorValidator(string(v)); err != nil {
			return &ValidationError{Name: "proration_behavior", err: fmt.Errorf(`ent: validator failed for field "Subscription.proration_behavior": %w`, err)}
		}
	}
	if _, ok := sc.mutation.EnableTrueUp(); !ok {
		return &ValidationError{Name: "enable_true_up", err: errors.New(`ent: missing required field "Subscription.enable_true_up"`)}
	}
	return nil
}

func (sc *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Subscription.ID type: %T", _spec.ID.Value)
		}
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeString))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.TenantID(); ok {
		_spec.SetField(subscription.FieldTenantID, field.TypeString, value)
		_node.TenantID = value
	}
	if value, ok := sc.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(subscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := sc.mutation.CreatedBy(); ok {
		_spec.SetField(subscription.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := sc.mutation.UpdatedBy(); ok {
		_spec.SetField(subscription.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := sc.mutation.EnvironmentID(); ok {
		_spec.SetField(subscription.FieldEnvironmentID, field.TypeString, value)
		_node.EnvironmentID = value
	}
	if value, ok := sc.mutation.LookupKey(); ok {
		_spec.SetField(subscription.FieldLookupKey, field.TypeString, value)
		_node.LookupKey = value
	}
	if value, ok := sc.mutation.CustomerID(); ok {
		_spec.SetField(subscription.FieldCustomerID, field.TypeString, value)
		_node.CustomerID = value
	}
	if value, ok := sc.mutation.PlanID(); ok {
		_spec.SetField(subscription.FieldPlanID, field.TypeString, value)
		_node.PlanID = value
	}
	if value, ok := sc.mutation.SubscriptionStatus(); ok {
		_spec.SetField(subscription.FieldSubscriptionStatus, field.TypeString, value)
		_node.SubscriptionStatus = value
	}
	if value, ok := sc.mutation.Currency(); ok {
		_spec.SetField(subscription.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := sc.mutation.BillingAnchor(); ok {
		_spec.SetField(subscription.FieldBillingAnchor, field.TypeTime, value)
		_node.BillingAnchor = value
	}
	if value, ok := sc.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := sc.mutation.EndDate(); ok {
		_spec.SetField(subscription.FieldEndDate, field.TypeTime, value)
		_node.EndDate = &value
	}
	if value, ok := sc.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = value
	}
	if value, ok := sc.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = value
	}
	if value, ok := sc.mutation.CancelledAt(); ok {
		_spec.SetField(subscription.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := sc.mutation.CancelAt(); ok {
		_spec.SetField(subscription.FieldCancelAt, field.TypeTime, value)
		_node.CancelAt = &value
	}
	if value, ok := sc.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
		_node.CancelAtPeriodEnd = value
	}
	if value, ok := sc.mutation.TrialStart(); ok {
		_spec.SetField(subscription.FieldTrialStart, field.TypeTime, value)
		_node.TrialStart = &value
	}
	if value, ok := sc.mutation.TrialEnd(); ok {
		_spec.SetField(subscription.FieldTrialEnd, field.TypeTime, value)
		_node.TrialEnd = &value
	}
	if value, ok := sc.mutation.BillingCadence(); ok {
		_spec.SetField(subscription.FieldBillingCadence, field.TypeString, value)
		_node.BillingCadence = value
	}
	if value, ok := sc.mutation.BillingPeriod(); ok {
		_spec.SetField(subscription.FieldBillingPeriod, field.TypeString, value)
		_node.BillingPeriod = value
	}
	if value, ok := sc.mutation.BillingPeriodCount(); ok {
		_spec.SetField(subscription.FieldBillingPeriodCount, field.TypeInt, value)
		_node.BillingPeriodCount = value
	}
	if value, ok := sc.mutation.Version(); ok {
		_spec.SetField(subscription.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := sc.mutation.Metadata(); ok {
		_spec.SetField(subscription.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := sc.mutation.PauseStatus(); ok {
		_spec.SetField(subscription.FieldPauseStatus, field.TypeString, value)
		_node.PauseStatus = value
	}
	if value, ok := sc.mutation.ActivePauseID(); ok {
		_spec.SetField(subscription.FieldActivePauseID, field.TypeString, value)
		_node.ActivePauseID = &value
	}
	if value, ok := sc.mutation.BillingCycle(); ok {
		_spec.SetField(subscription.FieldBillingCycle, field.TypeString, value)
		_node.BillingCycle = value
	}
	if value, ok := sc.mutation.CommitmentAmount(); ok {
		_spec.SetField(subscription.FieldCommitmentAmount, field.TypeOther, value)
		_node.CommitmentAmount = &value
	}
	if value, ok := sc.mutation.OverageFactor(); ok {
		_spec.SetField(subscription.FieldOverageFactor, field.TypeOther, value)
		_node.OverageFactor = &value
	}
	if value, ok := sc.mutation.PaymentBehavior(); ok {
		_spec.SetField(subscription.FieldPaymentBehavior, field.TypeString, value)
		_node.PaymentBehavior = value
	}
	if value, ok := sc.mutation.CollectionMethod(); ok {
		_spec.SetField(subscription.FieldCollectionMethod, field.TypeString, value)
		_node.CollectionMethod = value
	}
	if value, ok := sc.mutation.GatewayPaymentMethodID(); ok {
		_spec.SetField(subscription.FieldGatewayPaymentMethodID, field.TypeString, value)
		_node.GatewayPaymentMethodID = value
	}
	if value, ok := sc.mutation.InvoiceCadence(); ok {
		_spec.SetField(subscription.FieldInvoiceCadence, field.TypeString, value)
		_node.InvoiceCadence = value
	}
	if value, ok := sc.mutation.CustomerTimezone(); ok {
		_spec.SetField(subscription.FieldCustomerTimezone, field.TypeString, value)
		_node.CustomerTimezone = value
	}
	if value, ok := sc.mutation.ProrationBehavior(); ok {
		_spec.SetField(subscription.FieldProrationBehavior, field.TypeString, value)
		_node.ProrationBehavior = value
	}
	if value, ok := sc.mutation.EnableTrueUp(); ok {
		_spec.SetField(subscription.FieldEnableTrueUp, field.TypeBool, value)
		_node.EnableTrueUp = value
	}
	if nodes := sc.mutation.LineItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.LineItemsTable,
			Columns: []string{subscription.LineItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionlineitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PausesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PausesTable,
			Columns: []string{subscription.PausesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionpause.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PhasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.PhasesTable,
			Columns: []string{subscription.PhasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscriptionphase.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.CreditGrantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CreditGrantsTable,
			Columns: []string{subscription.CreditGrantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrant.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.CouponAssociationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponAssociationsTable,
			Columns: []string{subscription.CouponAssociationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponassociation.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.CouponApplicationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.CouponApplicationsTable,
			Columns: []string{subscription.CouponApplicationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(couponapplication.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.InvoicingCustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subscription.InvoicingCustomerTable,
			Columns: []string{subscription.InvoicingCustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InvoicingCustomerID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionCreate
}

// Save creates the Subscription entities in the database.
func (scb *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Subscription, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
